### ISSUE TITLE
BlurFilter: Resolution quality issue with RenderTexture

### ISSUE THREAD

**Issue by Adolio** [Gamua/Starling-Framework#1007]
## Introduction
When playing around with ```BlurFilter``` resolution, I noticed a rendering quality difference from normal rendering versus using ```RenderTexture```.

## Context
This has been tested on ```AIR 26``` with ```Starling master branch``` & ```Starling v2.2```.

## How to reproduce?
Here is a sample code to reproduce: [StarlingMain.as.txt](https://github.com/Gamua/Starling-Framework/files/1485520/StarlingMain.as.txt)

## Results
The following images show the quality artefacts (with resolution of ```0.25```):

**Normal rendering**
![screen shot 11-19-17 at 12 49 pm](https://user-images.githubusercontent.com/1126990/32990557-b0151a8e-cd2b-11e7-8982-387bbe466492.PNG)

**Rendering through RenderTexture**
![screen shot 11-19-17 at 12 50 pm](https://user-images.githubusercontent.com/1126990/32990558-b02afb06-cd2b-11e7-9168-e403d6284fe5.PNG)

**Comment by PrimaryFeather** [comment]
Wow — interesting! I'll look into it.

**Comment by PrimaryFeather** [comment]
The problem should now be fixed!

The problem was that the _BlurFilter_ has problems with the resolution property in general. The issue you reported could e.g. even be reproduced without a _RenderTexture_ with this simple code:

```as3
quad.filter = new BlurFilter(1, 1, 0.25);
quad.filter.alwaysDrawToBackBuffer = true;
```

What happens is that the filter, as part of an optimization process, draws directly to the back buffer in the final pass. That means, though, that the resolution of the input texture (`0.25`) doesn't match the resolution it is rendered to (`1.0`). And the blur algorithm doesn't like that at all! :wink:

The solution is to avoid that "optimization" when the resolution is not `1.0`.

Memo to myself: I also need to look at _DropShadow-_ and _GlowFilter_. They support a `resolution` parameter, but that leads to similar problems. It's just not as easily visible, since the blurred area is tinted in a single color.

**Comment by Adolio** [comment]
I confirm that this is now fixed for the ```BlurFilter```. 😃 Nice catch!

Thanks for the quick reaction & the explanations @PrimaryFeather!

**Comment by PrimaryFeather** [comment]
You're welcome, Aurélien! Thanks for trying it out! :smile:
