### ISSUE TITLE
After TouchPhase.ENDED, TouchPhase.HOVER happens again only after mouse moves

### ISSUE THREAD

**Issue by joshtynjala** [Gamua/Starling-Framework#146]
If the mouse remains over the same target after a TouchEvent with TouchPhase.ENDED, a TouchEvent with TouchPhase.HOVER should be dispatched immediately. Currently, a TouchEvent with TouchPhase.HOVER will only be dispatched after the mouse has moved again.

For a button component, after you click the button, the current behavior means that the button will not know to return to the hover state until you move the mouse. It is possible to manually hitTest() to see if the mouse is still over the button. However, Starling doesn't consider this to be a real hover, and that's leading to buggy behavior . If the button moves to a new position that is not under the mouse after the button has manually detected that it should be in its hover state, and the mouse hasn't moved yet to make Starling recognize the hover, the button will receive no event to indicate that it should leave its hover state and return to its up state.

This situation is currently happening in Foxhole. The ToggleSwitch component has a thumb that is a Button component. If you click the thumb, it will toggle selection, and the thumb will animate to a new position on the other side of the ToggleSwitch. The thumb remains in the hover state because it has moved away from the mouse, but Starling hasn't acknowledged the hover since the mouse remained stationary after the click.

**Comment by subdan** [comment]
Hi, Daniel. Do you plan to fix this issue?

**Comment by PrimaryFeather** [comment]
Thanks for the reminder — I must admit I forgot about this one, since it wasn't on the radar for a long time. I'll see what I can do!

**Comment by PrimaryFeather** [comment]
I just changed the code as suggested by Josh: each touch that's in the HOVER phase is checked once per frame: if the touch target has changed (because the object or one of its parents have moved), the touch is treated as if the touch itself had moved. That way, it immediately receives an appropriate event.

That fixes the sample you posted (in 2013 😦) Josh! Please let me know if that's what you wanted, and close the issue in that case.

Sorry for not fixing this for such a long time! Unfortunately, I've got the tendency to prioritise the stuff people shout out loudest about ... so I somehow forgot about it. Feel free to shout at me from time to time! :wink:

**Comment by joshtynjala** [comment]
Thanks, Daniel! Everything seems to be working nicely now.

**Comment by PrimaryFeather** [comment]
Awesome! Thanks for trying it out – and, again, sorry that it took so long. 😬
