### ISSUE TITLE
In mobile IOS/android. The upper half of the text will cut off. 

### ISSUE THREAD

**Issue by ghost** [Gamua/Starling-Framework#174]
In mobile, the upper half of the text will cut off when the size is bigger than the default font size (12). Seem the native text field will not resize correctly after embedFonts change.

Fix:
Edit the starling.text.TextField and add a line.

``` javascript
// we try embedded fonts first, non-embedded fonts are just a fallback
if (sNativeTextField.textWidth == 0.0 || sNativeTextField.textHeight == 0.0){
sNativeTextField.embedFonts = false;
sNativeTextField.setTextFormat(textFormat); // I add this line to renew the text
}
```

**Comment by UmberFunk** [comment]
Hi Daniel,

We have the same problem in our project. It happens when stage.quality = StageQuality.LOW;

AIR 18.0.0.199 and Starling 1.7

I uploaded simplified project here:
http://bonsters.co/_files/TEXTCUT.rar

Link to forum post:
http://forum.starling-framework.org/topic/texfields-with-device-fonts-are-cropped-on-android

Irakli

**Comment by PrimaryFeather** [comment]
The problem with "StageQuality.LOW" is something I can't do anything about. As mentioned in the forum, I added that information to the [Starling Wiki](http://wiki.starling-framework.org/manual/displaying_text) — hopefully, that makes it easier for developers to find out about the problem. Thanks again for the suggestion! =)

**Comment by leminhduc** [comment]
Hi Daniel, 

I face this issue too. I use AIR 19.0.0 & latest Starling build & StageQuality.HIGH

 // we try embedded fonts first, non-embedded fonts are just a fallback
if (sNativeTextField.textWidth == 0.0 || sNativeTextField.textHeight == 0.0)
{
	sNativeTextField.embedFonts = false;
}

On Ipad mini & desktop , it works fine 

On Iphone 5, after that line, textWidth  & textHeight remain value 0 !
Furthermore,  (textOffsetX + filterOffset.x) / scale   and (textOffsetY + filterOffset.y) / scale also wrong. 


I try the above suggestion : sNativeTextField.setTextFormat(textFormat); 
=> textWidth   & textHeight are reset correctly  
but (textOffsetX + filterOffset.x) / scale   and (textOffsetY + filterOffset.y) / scale  still wrong. 

Thank
David

**Comment by PrimaryFeather** [comment]
Sorry for the late reply, I was quite busy with the v2.0 launch!

Could you maybe set up a sample zip-file, including the code you're using to display the text and the font you're embedding?

I do most of my testing on iOS, and I haven't seen any problems on specific devices there. But who knows ... :-/

**Comment by leminhduc** [comment]
Hi Daniel, 

I did not use embedded font. I use native font "_sans"

_textField.autoScale = false; // it is starling.text.TextField
_textField.autoSize = TextFieldAutoSize.HORIZONTAL;
_textField.vAlign = VAlign.CENTER;  // VAlign.TOP alignment is wrong.

_textField.text = "An example message";

var currentTextW:Number = _textField.textBounds.width + 4;


I trace textBounds() => it calls redraw() => createRenderedContents()  => renderText(scale, mTextBounds)  

On Iphone 5,  AIR 19.0.0 & latest Starling build & StageQuality.HIGH, after 
if (sNativeTextField.textWidth == 0.0 || sNativeTextField.textHeight == 0.0)
            {
				sNativeTextField.embedFonts = false;
.....

after that line, textWidth & textHeight are still 0. 

If I call sNativeTextField.setTextFormat(textFormat);  => textHeight  is correct, but textWidth is still 0

So I have to reset everything to get correct format
				sNativeTextField.defaultTextFormat = textFormat;
				sNativeTextField.width = width;
				sNativeTextField.height = height;
				if (mIsHtmlText) sNativeTextField.htmlText = mText;
				else             sNativeTextField.text     = mText;


The bug happens in my project and (sorry) I don't know how to strip out a small test project. 
If you have your own test case project that can share, pls give me, I can test your test on my iphone5 & feedback to you.

Thank very much
David

**Comment by leminhduc** [comment]
Hi Daniel, 

On Iphone 5, AIR 19.0.0 & latest Starling build & StageQuality.HIGH
Kindly see the debug data here
[http://gamecotstudio.com/guppybox/debug.zip](url)

1.jpg :  assign text to _textField
2.jpg :  breakpoint before setting sNativeTextField.embedFonts = true  
2_sNativeTextField_at_step_2.txt   => you can see value of textWidth = 2819, textHeight = 26

3.jpg : breakpoint after setting sNativeTextField.embedFonts = false => you can see value of textWidth = 0, textHeight = 0  (3_sNativeTextField_at_step_3.txt)

4.jpg : result: unable to see the text 

myIphone5Data.PNG  : my iphone5 data.

If you compare 2_sNativeTextField_at_step_2.txt vs  3_sNativeTextField_at_step_3.txt, you can see the different. 

Wish that you could find the error. I do think this is the bug of Adobe Air, not your code :(

Thank
David

**Comment by PrimaryFeather** [comment]
Thanks for the additional information! I'll look into it as soon as I've got some more time — right now, I've got a lot of work at my hands after the 2.0 release. ;-)

**Comment by leminhduc** [comment]
Hi Daniel, 

Here is an easy way for you to reproduce this bug:

Install BlueStacks 2 at http://www.bluestacks.com/, build debug apk and set breakpoint in this line sNativeTextField.embedFonts = false;
I can reproduce this bug everytime on this simulator.


This bug happens in Starling 2.0 too ! And I have to apply similar hack in TrueTypeCompositor.as to fix it : 
            if (sNativeTextField.textWidth == 0.0 || sNativeTextField.textHeight == 0.0)
            {
				sNativeTextField.embedFonts = false;
				
				// I have to reset everything to get correct format
				sNativeTextField.defaultTextFormat = sNativeFormat;
				sNativeTextField.width  = scaledWidth;
				sNativeTextField.height = scaledHeight;

				if (options.isHtmlText) sNativeTextField.htmlText = text;
				else                    sNativeTextField.text     = text;
	 }


One more Truetype text bug on Starling 2.0 : htmlText rendered as empty
-> on desktop : can see htmlText but all the format like <font color='#99FF00'> are not applied
-> on Mobile (ios / android / BlueStacks simulator) : empty string.

Please please address this issue.
Thank very much
David

**Comment by PrimaryFeather** [comment]
When you say: "set breakpoint in this line" — does that mean the error only appears when I set this breakpoint? Or it's always there when using this simulator, and the breakpoint is just a good starting point to see what's going on? Thx! =)

**Comment by leminhduc** [comment]
Hi Daniel, 

The bug is always there when using the simulator & iphone 5.  "set breakpoint in this line"  to help you see what is going on!

I strongly believe this is internal Flash issue, as I see the behavior of sNativeTextField change randomly after embedFonts = false. 

Is there anyway to not use the line embedFonts = true to test ? In my project, I use Font.enumerateFonts() to check. 


One more issue with "htmlText rendered as empty"  : even when I use embededFont, the html tag <font color=...> has no effect.

Thank!

**Comment by PrimaryFeather** [comment]
<blockquote>Is there anyway to not use the line embedFonts = true to test ? In my project, I use Font.enumerateFonts() to check.</blockquote> 

I must admit I wasn't aware of that API! That would be a much cleaner solution — I'll look into that!

**Comment by PrimaryFeather** [comment]
I just added a check using the `Font.enumerateFonts()` method in the master branch. Could you try if that helps?

**Comment by leminhduc** [comment]
Hi Daniel, 

I've tried your solution, the array sEmbeddedFonts is always empty. I guess TrueTypeCompositor is constructed earlier than the time I embed fonts. It would be an issue as user may need to load & embed font at runtime (i.e change language option).

So I have to put  sEmbeddedFonts = Font.enumerateFonts(false); inside isEmbeddedFont function to get the latest array => which could be a potential performance issue.

Yet even we can avoid setting "embedFonts = true", the text still does not appear. I think there is a bug of offsetY: 

My text is : "Forgot login?" , 
isHtmlText = false, hAlign = Align.CENTER

scaledWidth = 843.9560439560439
scaledHeight = 42.1978021978022

-> textWidth = 135  -> bitmapWidth = 139
-> textHeight = 27  -> bitmapHeight = 31

-> offsetX = 352.47802197802196
-> offsetY = 0 ? You don't have this variable ?  -> should it be able to set it? 


In Starling 1.8, we are able to set VAlign of text, and it affect the drawMatrix directly:
            var textOffsetY:Number = 0.0;
            if (vAlign == VAlign.TOP)         textOffsetY = 2; // flash adds a 2 pixel offset
            else if (vAlign == VAlign.CENTER) textOffsetY = (height - textHeight) / 2.0;
            else if (vAlign == VAlign.BOTTOM) textOffsetY =  height - textHeight - 2;
           ......
            var drawMatrix:Matrix = new Matrix(1, 0, 0, 1, filterOffset.x, filterOffset.y + int(textOffsetY)-2);

But in Starling 2.0, you don't change offsetY ? 
           sHelperMatrix.setTo(1, 0, 0, 1, -offsetX, 0);
So the text scaledHeight is 42 -> draw to bitmapHeight 31 -> I suspect the text is cut off or empty due to it draw in wrong area?

I saw you put similar code to fillMeshBatch  
            if (format.verticalAlign == Align.TOP) sHelperQuad.y = 0;
            else if (format.verticalAlign == Align.CENTER) sHelperQuad.y = int((height - texture.height) / 2);
            else sHelperQuad.y = height - texture.height;

But this code is already after BitmapData is drawn :(


I compare the code with Starling 1.8, there is quite a big change. 
Btw, are you able to run BlueStack? :)

Thank
David

**Comment by PrimaryFeather** [comment]
Damn, I had never tried to load embedded fonts at runtime ... that must of course be taken into account. May I ask how you're doing that? Perhaps there is a callback or event I can use to automatically refresh `sEmbeddedFonts` when that happens.

Other than that, it seems we're on the right track! It's no problem to change the order of calls, that's a good idea.

I didn't try BlueStack yet, because I hoped my fix from yesterday would do the trick. But I might be able to run a test on an iPhone 5 today.

**Comment by PrimaryFeather** [comment]
I just added the method `TextField.updateEmbeddedFonts()`. You need to call that after you loaded an embedded font at runtime. I'd have preferred to automate this, but I didn't find any way of doing so.

Still, I think it's a clean solution, and still less error-prone as in classic Flash. Now I just hope that it fixes your original problem, as well. Just let me know! :wink:

**Comment by leminhduc** [comment]
hi Daniel!

Thank for your quick response! Yes it fixes my problems! 

A small performance issue:  Flash have no function to remove embedFonts after register. My app supports 7 languages, each language uses 4 fonts. User can switch languages at runtime. 
In worst case if he changes all 7 languages, the array sEmbeddedFonts will have 7 x 4 = 28 items. So everytime one textField created, it needs to loop this long list to check. 

Here is my optimization, hope you are ok with it:

        private static var sEmbeddedFontDict:Dictionary = new Dictionary;
        private static function isEmbeddedFont(format:TextFormat):Boolean
        {
			var fontName:String = format.font;
			var fontStyle:String = (format.bold && format.italic)? FontStyle.BOLD_ITALIC : (format.bold? FontStyle.BOLD : (format.italic? FontStyle.ITALIC : FontStyle.REGULAR));
			
			if (sEmbeddedFontDict[fontName] == null)
				sEmbeddedFontDict[fontName] = new Dictionary;
			
			if (sEmbeddedFontDict[fontName][fontStyle] == null)
			{
				if (sEmbeddedFonts == null)
					sEmbeddedFonts = Font.enumerateFonts(false);
					
				for each (var font:Font in sEmbeddedFonts)
				{
					if (fontName == font.fontName && fontStyle == font.fontStyle)
					{
						sEmbeddedFontDict[fontName][fontStyle] = true;
						return true;
					}
				}
			}
			
            return false;
        }

**Comment by PrimaryFeather** [comment]
I'm glad to hear that this fixes your problems!
As for the performance, I'm busy today but I'll look into it. Although even with 28 items, I don't think it's much of a problem. Creating / updating a TTF TextField is a slow operation anyway, I don't think that loop will make a big impact. Something to analyze with Scout. :-)
