### ISSUE TITLE
FragmentFilters Interface

### ISSUE THREAD

**Issue by shin10** [Gamua/Starling-Framework#391]
Hi Daniel,

the last weeks I got lost somehow in writing FragmentFilters and I recognized that some Filters will only be possible with overriding the render function. (That recently came up with a 2.5D Filter, ... I know, bad idea ... but will also be an issue with the BloomFilter I had in mind)

Unfortunately overriding is not working well, since a lot of private variables/functions are used in your render/renderPasses functions. My workaround was disposing the filter right in the subclass's constructor and adding almost a complete copy of the FragmentFilter super class to my subclass, which is obviously bad. But I couldn't find a better way to make it work without customizing starling, which would make the filters useless for others.

So I'd like to ask whether you could implement a IFragmentFilter interface to Starling 1.4 or at least change the private functions/vars to protected, which would also be working, but as I guess be less efficient. What ever you like best. That would be really awesome.

Thanks in advance

Michael

**Comment by PrimaryFeather** [comment]
Hey guys, if any of you are still working with filters, I'd be extremely happy about any feedback on the new filter API of Starling 2! Right now, there's still time to change it, so any feedback would be welcome. :smile:

There's still no "IFragmentFilter" interface, but instead I tried to make filters more flexible and easier to understand. For example, you can combine several filters into one (via the new "FilterChain"), use other filters for specific render passes, etc.

Here's the API reference:
http://doc.starling-framework.org/v2.0/starling/filters/package-detail.html

The code can be found in the "v2.0" branch. 
Let me know if there's anything you want to comment on — the good, the bad, and the ugly! :wink:
Thanks a lot in advance!

**Comment by yuheng85** [comment]
Hi, Daniel

Is it posible to have a hue property of ColorMatrixFilter? My use case is having a property vs a method will make Starling Builder easier to support filters. I think adjusting hue value has the most use case for us.

**Comment by shin10** [comment]
Hi Daniel!

Great news! I must admit, that I unfortunatelly haven't done Flash stuff for about over a year now, but recently thought about starting a little project for myself in near future.
Right now I'm busy with another private thing, but I hope to finish it soon. So maybe I can check it out next week. I hope that's not too late.

By the way. I just checked the forum thread about your other changes. It reads like it makes my FFParticleSystem fork of your PS obsolete. Is that right? Wouldn't be that bad, since I realised how bad I'm in supporting that stuff right now. I definitely need some time off and more play time. :D

Cheers

**Comment by PrimaryFeather** [comment]
@yuheng85 My original plan would have been to do just that, actually! However, it turned out that it's not easy to combine such a property and still providing access to the underlying matrix.

It's similar to display objects: when you update x/y/scale etc., the transformation matrix is updated; and if you update the transformation matrix, x/y/scale etc. are going to be updated again to reflect the matrix contents. It took me (with my limited math skills) a while to come up with the formula to get from the matrix to those properties.

I would have to do the same for the color matrix, and that's simply way over my head — if it's possible at all, because e.g. calling the "tint" method would also effect the hue, so the properties are not entirely orthogonal.

The solution I would propose is to add a "ColorFilter" instead, that uses the "ColorMatrixFilter" internally (with the new API, that's possible to do via composition instead of inheritance) that doesn't provide access to the matrix, but instead only provides properties for "hue", "contrast", etc., and calculates the matrix according to those values. If you need any help with that, just let me know!

@shin10 

Thanks a lot for your reply, especially considering that you're not into Flash stuff right now! If you find the time, it would mean a lot to me if you could take a look at the API. :smile:

As for the particle system ... well, I don't think it's really obsolete. The new version of my particle system does have a `batchable` property and can thus be batched with other particle systems, but I know that you did some great other optimizations that my particle system doesn't have. But at least for some users, my version will now be acceptable, I guess. :wink:

Either way: yes, I can definitely recommend more play time, haha!!! :video_game: :fries: :bicyclist:

**Comment by PrimaryFeather** [comment]
In the meantime, I was in contact with @shin10 via email, and it seems that the new API is powerful enough for most of his wishes! :wink: 

So I think it's time to close this issue! Thanks again for all the fruitful suggestions.
