### ISSUE TITLE
ColorMatrixFilter clipping SubTexture with frame

### ISSUE THREAD

**Issue by butaca** [Gamua/Starling-Framework#645]
When applying a ColorMatrixFilter to an Image with a SubTexture which has frame, it is drown clipped. This doesn't happen If the frame is the same as the region. I assume the filter is not taking the right bounds or something similar.

Using SubTextures with a frame is a common scenario since I'm using texture atlases with cropped textures.

I tried with another filter (BlurFilter) and the clipping doesn't happen.

Maybe is unrelated but, calling getBounds on an Image (stage space) with different frame positions for its SubTexture result in the same rect. Is this the expected behaviour?

**Comment by PrimaryFeather** [comment]
@Butaca, first of all, I have to apologize for the long delay until I could look into this! First there was the Starling 1.6 release that kept me busy, and then some other things ... 

But finally, I could look at your sample!

The first thing that caught my eye is that you're using the "frame" rectangle not the way it was designed for. A frame rectangle can be used to make a texture *bigger* than what the texture data would suggest, but never smaller. The main use for that is if you've got a texture that has a transparent border; instead of filling up GPU memory with that transparent pixels, you crop them away (e.g. via a tool like TexturePacker) and then let Starling restore the cropped off area with the frame.

So e.g. if you've got this texture, and it's 75x75 pixels:

```
-------
|     |
|  X  |
|     |
-------
```

You could crop it to this (25x25 pixels)
```
---  
|X|  
---  
```

That new texture takes up less memory, but it also behaves different than the original one. (E.g. an image that uses this texture will have a width of `25`, not `75`.) So you add a frame:

```as3
var frame:Rectangle = new Rectangle(-25, -25, 75, 75);
var subTexture:SubTexture = new SubTexture(texture, null, false, frame);

var image:Image = new Image(subTexture);
trace(texture.width) // -> 25
trace(image.width); // -> 75
```

As you can see, the `x` and `y` coordinates of the SubTexture are negative. You start at the texture's origin (the top left spot of the `X`), and then move -25 in x direction and -25 in y direction. That's the root of the frame.

Now, an image that uses this texture will behave just like an image that was created with the original texture. (Returning a `width` of `75`.)

The texture still returns `25`, though; that's something I don't like myself (I'd prefer if the texture would already behave in the correct way), but that's the way it is currently. 

Does that explain it a little better?

**Comment by butaca** [comment]
Thanks @PrimaryFeather for your kind and detailed response. Sorry for the delay, I've been very busy.

The main reason I'm using the texture frame is because I'm generating the atlas xml and need to set a "pivot point" to each sprite in the atlas. Reading thought the documentation I reached the texture frame and thought it was just a region within the SubTexture (the area after the crop). So, I manipulated the frame values and achieved the desired effect (the pivot point) but by chance, because now I see it was designed in a different way than I thought.

Regardless my use case, IMHO I didn't find the design and documentation of this feature intuitive. If I understood correctly, with the frame x and y you set the cropped area from top-left and in conjunction with the frame width and height, the area cropped from bottom-right. Am I right? And, maybe the API should check if the frame is invalid and notify the error somehow.

Thanks again for your time and kind response.

**Comment by PrimaryFeather** [comment]
No worries about the delay!

Mhm, the texture frame is indeed quite confusing — I must admit it was added as an after-thought (solely to support the "trim" feature of Texture Packer), and that shows. It's not intended to be used as a pivot point.

Indeed, the frame starts at the top left point of the cropped texture. The coordinates follow the standard Starling axes (x goes right, y goes down), so the x and y will always be negative. Then, the width and heights are measured from the root of the *frame*, i.e. the point you end up when you follow the frame.x and frame.y values.

May I ask where you looked for the documentation on this? There's a quick description in the overview of the [texture class](http://doc.starling-framework.org/core/starling/textures/Texture.html), but that could definitely be expanded; and it might not be the place where people look for it.

In any case, I should at least log out a warning when the frame lies somewhere within the texture — that's an excellent idea, and will give people a heads-up just in time. I'll do that!
