### ISSUE TITLE
add timestamp getter in Juggler

### ISSUE THREAD

**Issue by commovere** [Gamua/Starling-Framework#660]
I think it can help to reduce amount of getTimer() calls.

**Comment by commovere** [comment]
no, elapsedTime is the total life time of the juggler, but in some situations I need to get life time of my custom objects. Code like this
```actioncript
if(getTimer() - myObject.creationTime>= someDurationConstant){
    doSomething();
}
```
can be replaced by this
```actioncript
if(juggler.timeStamp- myObject.creationTime>= someDurationConstant){
    doSomething();
}
```
maybe it will be easier to create getter of mLastFrameTimestamp in Starling class

**Comment by PrimaryFeather** [comment]
I'm not sure I understand your requirements entirely ...!

If you call "Starling.current.juggler.elapsedTime", it should be equivalent to "getTimer()", because that Juggler is advanced during the lifetime of Starling. So that should be exactly what you need — if you're looking for a replacement of "getTimer()". Otherwise, please try to explain in a little more detail, so that I understand your requirements a little better. Thanks!! :smile:

**Comment by commovere** [comment]
>If you call "Starling.current.juggler.elapsedTime", it should be equivalent to "getTimer()"

actually Starling.current.juggler.elapsedTime == getTimer() - jugglerCreationTime
now I see that  Starling.current.lastFrameTimestamp is what I`m loking for.
So it would be great to have this getter

**Comment by PrimaryFeather** [comment]
Hm, sorry, I still don't see why this would be strictly necessary. The "getTimer()" function is a function that's internal to Flash, i.e. it's not provided by Starling. Starling's time mechanisms are those provided with the juggler and the "passedTime" property in the ENTER_FRAME event. Another way of accessing "getTimer()" would be redundant in my opinion.

I'd recommend you store the current frame time once each frame via an "ENTER_FRAME" event handler, and access it from there throughout your game. I hope you can understand my reasoning and can live with that workaround.
