### ISSUE TITLE
Data store on starling.display.DisplayObject for referencing custom wrapper classes when using composition vs inheritance

### ISSUE THREAD

**Issue by MartyWallace** [Gamua/Starling-Framework#665]
It would be useful for the sake of composition to have a data field on `DisplayObject`, similar to Box2D's `b2Body` class. What I am trying to is have my own graphics classes that wrap Starling display classes, however I need to have a reference to my wrapper classes via the Starling objects to determine the correct values for `.parent` etc.

**Comment by MartyWallace** [comment]
(Sorry about the poor composition of this issue, I don't recommend using GitHub on a mobile device...).

**Comment by b005t3r** [comment]
I think that in Box2D or Nape this is a workaround for not being able to use inheritance for creating custom bodies.

**Comment by MartyWallace** [comment]
@b005t3r As a better example, I need to rewrite some methods to return my own Vector2D object instead of a `flash.geom.Point`, e.g. for `localToGlobal`, but obviously I can't modify the existing signatures for those methods to do so via inheritance, so composition is necessary here.

**Comment by b005t3r** [comment]
Subclass and add your own methods which would return this objects or make your Vector2D inherit Point and you're able to return Vector2D instances where Points are normally returned.

**Comment by MartyWallace** [comment]
@b005t3r If I start adding my own methods they will have to have different names and sit alongside the existing ones, which will make the class definition cluttered and ambiguous. I also can't extend Point because I need to have getter and setter methods for `x` and `y` which you can't create because they're public fields on Point, not getters and setters that you can override.

**Comment by b005t3r** [comment]
If know what you mean, but still it does sound better than adding a 'void pointer' to every DisplayObject. I'd go with extending Point and using its public members instead of properties (which sounds like not that bad idea because of AS3 poor method call performance).

And to be completely honest, I did chose to go this way with my own implementation of Point2D (which has few additional methods for spatial indexing, etc.):

https://github.com/b005t3r/MedKit/blob/master/src/medkit/geom/shapes/Point2D.as

**Comment by MartyWallace** [comment]
@b005t3r I need the getters and setters because my Vector2D object wraps a b2Vec2 and I need to have it updated when the x and y are updated on the Vector2D. This is only one example to demonstrate a broader need anyway, I wouldn't focus too heavily on this specific usage.

**Comment by PrimaryFeather** [comment]
Hm ... I'm not a particular fan of such generic add-on properties. 

One problem with them is that they might cause a conflict later on. Imagine one developer using that property to store some state information in that variable, let's say the information if the object is currently being hovered over with the mouse. A little later, the developer adds a library to the project that's used to create replay functionality (recording all display list modifications) to his game. That sounds really innocent — but it turns out that this library uses the same property to store serialization information (e.g. for a key/value store), which was previously used for the mouse state. 

Both developers had a really good reason to make use of that property; after all, they are both storing information that's needed on all display objects. That property can be used for anything, but only for one thing at a time. And that could lead to problems.

I know that I added such a property myself in the "Event" class. But I think the case is a little different here; events are typically created at one point in the code, and read at other places; they are not modified once they have been created — thus, there are less opportunities for problems. It's still not super-beautiful, but it can be useful (because you don't need to subclass "Event" all the time).

Does that make sense to you?

Any other voices and suggestions are welcome, by the way. (Thanks, Łukasz!)

**Comment by neolit123** [comment]
@MartyWallace
a hackerish solution, but how about using the DisplayObject "name" field as a unique String key to a manually maintained Dictionary where values are the data objects you require?

globalData[someDisplayObject.name] = { something: 1 };

this also leads to the problem described above - what would the .name field actually hold - just a name or for some uses a Dictionary key.

but framework wise, why does DisplayObject need the .data field anyway? what would you add in the description for the field in the docs?

i agree that having "data" in a DisplayObject to be a generic AS3 Object member is questionable. inheritance seems like the only sane solution here.

**Comment by MartyWallace** [comment]
@PrimaryFeather I admit that I would be extremely resistant to this kind of request were I in your position. To provide some context, I am trying to do with Starling what I have done with Box2D in [this package on a game framework I am working](https://github.com/MartyWallace/Sentinel/tree/master/src/sentinel/gameplay/physics) on. All I've done is rewritten a lot of the internal methods so that they return objects that my framework defines vs ones that Box2D defines internally (e.g. my `World.createBody()` returns a `sentinel.gameplay.physics.Body` vs a `b2Body`).

I have been using inheritance with Starling so far, [which you can see here](https://github.com/MartyWallace/Sentinel/tree/master/src/sentinel/framework/graphics), however each time I want to add a new bit of functionality to a Starling display object I am forced to add that logic to each individual class (`Sprite`, `TextField`, `MovieClip`, etc) which gets tedious and difficult to maintain. I am now also running into the issue discussed above where I want to have some of the existing `starling.display.DisplayObject` methods rewritten slightly (like I have done with my physics `World` vs the Box2D `b2World`).

Ultimately it would be nice to have something like:

<pre>
public class MyGraphics
{
    private var _base:starling.display.DisplayObject;

    public function get x():Number{ return _base.x; }
    public function set x(value:Number):void{ _base.x = value; }
    // ...etc
}
</pre>

But I get stuck when I need to start accessing nested values like `parent`:

<pre>
public function get parent():MyGraphics
{
    return _base.parent.{need reference to a MyGraphics instance here};
}
</pre>

For some additional background, I have [a Stack Overflow question](http://stackoverflow.com/questions/27007311/correct-way-to-deal-with-overriding-a-method-and-changing-the-argument-type-to-a) that talks about dealing with a very similar problem from the perspective of the person writing the framework.

As for the concerns you have with conflicting data being attached to something so generic, I agree with that but I think it could be mitigated almost entirely by changing the field from 'arbitrary' (`data:*`) to something more specific like a `facade` field that accepts an `IStarlingFacade` interface or similar. That way, the intent is clear at the very least.

With all of that said, I can see that this addition only covers a narrow set of use cases, so it's probably better that I add this logic in my own fork of Starling. I was just curious what your thoughts would be on the matter and whether you would consider it to go along with the other logic Starling offers for extensibility.

@neolit123 If it came to something like using a dictionary, I would bail on the idea entirely. Also, the `name` property has other usages which I don't intend to mess with.

**Comment by PrimaryFeather** [comment]
Thanks for the additional information and the insights into your problem! I can totally relate to that problem, of course. I guess since Starling (and the Flash API in general) are so heavily based on inheritance, building on it in a more composition-style library is more difficult than it should be.

I'd probably try my luck with @neolit123's approach, though without relying on the name property. AS3's Dictionary class uses strict equality (===) for key comparison, so you can directly use the object in question as a key. And since the Dictionary even supports weak keys, this won't lead to any cyclic reference problems (something that would otherwise pop up for sure sooner or later). The performance would have to be tested, of course, but my guess would be that it's not too problematic.

Maybe that's worth a shot! A nice side effect is that this would work with all kinds of libraries and frameworks, not just Starling.

In any case, I hope you understand that I don't want to add such a property at the current time. I will try to think of other possible solutions, though! 

BTW, good luck with "Sentinel"! It looks like a really interesting project — please keep me updated on the progress! If it's in a state you want to show to more Starling developers, just ping me, and I'll tweet/plus/etc. about it so that the community doesn't miss it! :-)

**Comment by neolit123** [comment]
(PrimaryFeather posted just now, but here is my extended comment. hope it helps...)

@MartyWallace 
i see your problem,

>
have been using inheritance with Starling so far, which you can see here, however each time I want to add a new bit of functionality to a Starling display object I am forced to add that logic to each individual class (Sprite, TextField, MovieClip, etc) which gets tedious and difficult to maintain. I am now also running into the issue discussed above where I want to have some of the existing starling.display.DisplayObject methods rewritten slightly (like I have done with my physics World vs the Box2D b2World).

it's not a matter of inheritance vs composition but a matter of how to mix them. your general approach is wrong here. if this was C++ you would have a diamond shape multi-inheritance problem, because you want, say, your Quad class to extend both Starling's Quad and the Starling DisplayObject you want modified. the way to solve multi-inheritance issues is to use a mixture of composition and inheritance. the same will happen with the flash display list and DisplayObject based classes.

the cleanest and least intrusive way to approach it is to create a wrapped display list where your classes no longer extend Starling's DisplayObject.

the composition example you posted above is in the right direction, expect you need to create at least a couple of base classes - MyDisplayObject and MyDisplayObjectContainer:
```
public class MyDisplayObject
{
    internal var _base:starling.display.DisplayObject;
}
```

also MyDisplayObject would need _base of type DisplayObject (or Object, or *) and MyDisplayObjectContainer that extends MyDisplayObject will sets _base to another type.

```
public function get parent():MyDisplayObjectContainer
{
    return _base.parent.{need reference to a MyDisplayObjectContainer instance here};
}
```

the Starling DisplayObjectContainer class (parent for this instance) should not be aware of some generic type. the way you approach this is the following:
```
public function get parent():MyGraphics
{
    return _parent;
}
```
and *you* maintain _parent via your wrapped display list pattern.

of course, if you have understood what direction i'm going for that with this type of composition + inheritance you will have to pretty much wrap *all public methods* of DisplayObject, DisplayObjecContainer and the classes that subclass them. also, there is a performance penalty.

> As for the concerns you have with conflicting data being attached to something so generic, I agree with that but I think it could be mitigated almost entirely by changing the field from 'arbitrary' (data:*) to something more specific like a facade field that accepts an IStarlingFacade interface or similar. That way, the intent is clear at the very least.

with any type (Interface, Object or *) the purpose of the reference itself will remains unclear and undefined. a "facade" in programming is a fancy yet poor excuse to explain API simplification.
on the other hand in this case the reference needs not "API simplification" but rather definition.

> With all of that said, I can see that this addition only covers a narrow set of use cases, so it's probably better that I add this logic in my own fork of Starling. I was just curious what your thoughts would be on the matter and whether you would consider it to go along with the other logic Starling offers for extensibility.

forking is your easiest solution ATM, i would think.
now, in terms of making this into some sort of a clever API extension perhaps others can comment further.

**Comment by PrimaryFeather** [comment]
Great post, @neolit123, those are really good arguments!
That's a really fruitful and interesting discussion, that's for sure! :smile:
