### ISSUE TITLE
Generalize the QuadBatch system to accept any triangle mesh

### ISSUE THREAD

**Issue by henke37** [Gamua/Starling-Framework#672]
I don't see a technical reason for why quad batches have to be limited to quads, as long as the data has the same vertex attributes, any mesh should work fine.

This should hopefully reduce the need for custom display objects to break batching.

**Comment by PrimaryFeather** [comment]
Yes, I totally agree. The whole "QuadBatch" system will be replaced in Starling 2.0; the current plan is to allow developers to create "Renderer" classes that replace this functionality. E.g. people will be able to define a default renderer for any object type, and this renderer will then be able to batch everything that it receives (whatever you define, be it Quads, Triangles, Shapes, etc).

But how exactly this will work out remains to be seen. As soon as I work on Starling 2.0, I'll publish alpha and beta versions for feedback! 

I'll close this issue for now, though, because it's just a part of my 2.0 plans. Nevertheless, thanks for the suggestion!
