### ISSUE TITLE
Some problem about setRenderTarget

### ISSUE THREAD

**Issue by tony851028** [Gamua/Starling-Framework#678]
private var diffuse:Texture;
				
		public function ObjectContainer() 
		{
			super();
			
			diffuse = Texture.empty(Starling.current.viewPortWidth, Starling.current.viewPortHeight, true, false, true, -1, Context3DTextureFormat.RGBA_HALF_FLOAT);
		}
		
		public override function render(support:RenderSupport, parentAlpha:Number):void
        {
			support.setRenderTarget(diffuse, Starling.current.antiAliasing)
			//Starling.context.setRenderToTexture(diffuse.base, false, Starling.current.antiAliasing);
			super.render(support, parentAlpha);
			support.setRenderTarget(null);
			//Starling.context.setRenderToBackBuffer();

			
			var image:Image = new Image(diffuse);
			
			support.pushMatrix();
            support.transformMatrix(image);
            support.blendMode = image.blendMode;
			image.render(support, alpha);
			support.blendMode = blendMode;
			support.popMatrix();
			
			image = null;
        }

I can't see anything in image.
if I comment applyClipRect() in RenderSupport , child.z = 0 is normal but child.z != 0 disappear

**Comment by tony851028** [comment]
I resolve it!!
Add clear function before render.

**Comment by PrimaryFeather** [comment]
Sorry for my late reply, I was too busy to look into it last week!

Yes, when you call "Texture.empty", it won't be initialized yet. You have to either call "clear" or upload some data before you can actually use it.

It's described in the API docs, but it's easy to overlook, agreed!
In any case, I think your issue is solved, right? Then I'll close it for now. Feel free to reopen it if there are further issues.
