### ISSUE TITLE
BitmapFont too lenient (silent fail) when not using BMFont XML format?

### ISSUE THREAD

**Issue by jamikado** [Gamua/Starling-Framework#684]
With this forum thread as a sample:
http://forum.starling-framework.org/topic/i-cant-show-bitmap-fonts-without-color-tint-help-me-please

Is it possible the current BitmapFont setup/parsing code is too lenient with its XML processing so that it silently fails to create a working BitmapFont when passed (for example) the text BMFont format?

Maybe BitmapFont should raise a warning when it isn't able to find at least a face attribute or any characters in the XML parsing phase to make it easier for a first time setup to debug the mistake?

**Comment by PrimaryFeather** [comment]
Wow, I wasn't aware of that! You're perfectly right, this should definitely cause a warning or an error. Otherwise, situations like the one you refer to can easily arise. I'll make that change!

**Comment by PrimaryFeather** [comment]
I added a check that "fontXml" must not be null when a texture is given (if both is null, it's fine, because that will create the "mini" font).

However, in his situation, it won't help much, I'm afraid. He used the following code:

```as3
var fontXML:XML = XML(new BitmapFontFNT());
```

... and this must have thrown an exception, because if the embedded data is not an XML, you can't convert it to one; I tried that. He's probably using the release player; and in that case, my new exception won't show up, either. ;-)

I'll tell him to use the debug player!

In any case, it still made sense to add that check. Thanks for the suggestion!!
