### ISSUE TITLE
DisplayObject's set filer

### ISSUE THREAD

**Issue by Oldes** [Gamua/Starling-Framework#693]
If you are setting a filter on object where already is filter, should not be the old one disposed first?

https://github.com/Gamua/Starling-Framework/blob/master/starling/src/starling/display/DisplayObject.as#L931

**Comment by jamikado** [comment]
Did you read the comments directly above this code? Daniel says explicitly why it isn't disposed
"Beware that a filter should NOT be attached to different objects simultaneously (for
* performance reasons). Furthermore, when you set this property to 'null' or
* assign a different filter, the previous filter is NOT disposed automatically
* (since you might want to reuse it)"

**Comment by Oldes** [comment]
Ah, there are also comments... :) Never mind.
