### ISSUE TITLE
Starling in JavaScript

### ISSUE THREAD

**Issue by bpq** [Gamua/Starling-Framework#694]
How difficult would it be to port this to JavaScript? I am wondering if there would be anyone interested in having a shot at it with me.

**Comment by jamikado** [comment]
http://forum.starling-framework.org/topic/starling-js-in-the-hands-of-away

**Comment by PrimaryFeather** [comment]
As Jeff mentioned, we once started a port, but then handed it over to the Away Foundation. They are now integrating it in the JS version of Away3D.

For me personally, I decided the time is not right for a port, because it would take away too much time from my AS3 Starling development. But it would definitely be doable, especially with the recent advancements in WebGL support.
