### ISSUE TITLE
Add PMA param to RenderTexture's constructor

### ISSUE THREAD

**Issue by b005t3r** [Gamua/Starling-Framework#696]
Currently all RenderTextures use premultiplied alpha. I'd like to create a RenderTexture with standard alpha, but there's no way to set it using RenderTexture's constructor. Please add it as one of the params.

**Comment by jamikado** [comment]
Isn't that because it won't work?
https://github.com/Gamua/Starling-Framework/issues/523

**Comment by b005t3r** [comment]
Hmm, I see that with PMA set to false subtransparent pixels are rendered darker. So is this an AIR bug? I mean, you can'y use a non-PMA texture as a render target?

**Comment by b005t3r** [comment]
I did some googling and found out that you should account for premultiplied alpha values when sampling a texture in AGAL. I wonder if you should also account for output texture alpha mode when rendering to texture?

Anyway, Starling code doesn't do that at any point, so maybe this is the source of all alpha problems?

**Comment by b005t3r** [comment]
OK, I've figured it out.

The thing is Starling's shaders don't account for PMA or non-PMA data when reading and outputting pixels (e.g. the shader which renders textured quads just outputs the input pixel without any processing, so for PMA input texture it always outputs PMA pixels, for non-PMA it always outputs non-PMA pixels). In a majority of cases, PMA textures are used (because loading PNGs always gives you a PMA texture), so having only PMA RenderTextures does also work in majority of cases, when rendering an Image to the texture. But as it is currently it won't work with non-PMA Images (like the ones created with ATF textures) rendered to a RenderTexture instance. Moreover, it won't work when rendering images created with different texture formats to a RenderTexture (rendering Images created form PNG and ATF files). 

The only solution I can think of is making Starling's shaders aware what pixel format they read and what is the expected output pixel format, which is probably not an easy task with the current version, but something to definitely keep in mind for Starling 2.0.

**Comment by PrimaryFeather** [comment]
Yes, this is a complicated topic ... and when I implemented all this, I even considered using the shaders to treat all texture data the right way (which I thought would be non-premultiplied). However, this has a few downsides; e.g. that the fragment shader would be a little more complex (which was truly an issue with hardware like the iPad 1), and that premultiplied alpha actually seems to be superior when it comes to blend factors! For example, non-PMA textures tend to produce black outlines; I just saw that pop up on the forum just a few days ago. More info on that topic [here](http://blogs.msdn.com/b/shawnhar/archive/2009/11/06/premultiplied-alpha.aspx), [here](http://home.comcast.net/%7Etom_forsyth/blog.wiki.html#[[Premultiplied%20alpha]]) and [here](http://blog.rarepebble.com/111/premultiplied-alpha-in-opengl/). So handling all textures equally is not desired, either.

Nevertheless, I never quite figured out what's happening with RenderTextures. Because even if I set them to "PMA = false" and draw only ATF textures, I get weird results ...

**Comment by b005t3r** [comment]
> Nevertheless, I never quite figured out what's happening with RenderTextures. Because even if I set them to "PMA = false" and draw only ATF textures, I get weird results ...

No idea why this would happen. Did you get the same results with non-PMA colored quads?

As for the "smart" shaders and conditional PMA to non-PAM conversion, etc. - for scenarios where a PMA texture is being rendered to a PMA texture (or where both are non-PMA) shaders won't have to do anything more than they do now. You just need to do the conversion when input and output have different PMA settings, which requires having 3 shaders for rendering textures instead of one and calling the right one if conversion is needed - QuadBatch already handles things like that (with tinted Quads), so this would be just another scenario, I think.

**Comment by b005t3r** [comment]
Daniel, if you made this change, I could prepare a test app for checking (on various devices hopefully) if this problem still exists (I mean AFTs rendering differently).

As for the darker/lighter halos around semi-transparent pixels when scaling or using mipmaps, this is a good point for using PMA textures where possible, but in general it's not that relevant, because there are tools (like TexturePacker) for processing non-PMA textures to work around that problem (adjacent fully transparent pixels have the same color set as the semi-transparent ones).

**Comment by PrimaryFeather** [comment]
<blockquote>Did you get the same results with non-PMA colored quads?</blockquote>

I don't remember, unfortunately. I'm going to have to revisit this once again, I'm afraid ...!
You're right about the tool support, of course; it's good to have such options. 
Thanks for your offer to help, I might make use of that!

**Comment by PrimaryFeather** [comment]
Starling 2 forces PMA for all textures (via the fragment shader), as was actually discussed in this thread.
Thus, this should no longer be an issue. Hooray! :smile:
