### ISSUE TITLE
The Stage3D API may not be used during background execution

### ISSUE THREAD

**Issue by hejiacong** [Gamua/Starling-Framework#699]
This issue is an Addition bug about an colsed issue https://github.com/Gamua/Starling-Framework/issues/397
Hey Daniel,not only the AssetManager would call "uploadFromBitmapData",but also the TextField.createRenderedContents.
The stack trace is here

Error: Error #3768: The Stage3D API may not be used during background execution on this operating system.
at flash.display3D.textures::RectangleTexture/uploadFromBitmapData()
at starling.textures::ConcreteTexture/uploadBitmapData()[D:\cn.gecko\client\starling\src\starling\textures\ConcreteTexture.as:133]
at starling.textures::Texture$/fromBitmapData()[D:\cn.gecko\client\starling\src\starling\textures\Texture.as:256]
at starling.text::TextField/createRenderedContents()[D:\cn.gecko\client\starling\src\starling\text\TextField.as:195]
at starling.text::TextField/redraw()[D:\cn.gecko\client\starling\src\starling\text\TextField.as:166]
at starling.text::TextField/getBounds()[D:\cn.gecko\client\starling\src\starling\text\TextField.as:502]
at starling.display::DisplayObject/get height()[D:\cn.gecko\client\starling\src\starling\display\DisplayObject.as:749]

**Comment by PrimaryFeather** [comment]
You're right, there are several places where "uploadFromBitmapData" is called without being guarded by "SystemUtil.executeWhenApplicationIsActive()". 

The point in #397 was that the URLLoader will cause code to be executed even though "background execution" is deactivated. And since the AssetManager uses the URLLoader, I added a workaround for that problem.

For other cases, developers have to take care about this manually. If I'd check for the application state every time I'm using Stage3D, performance would come to a crawl. It's simply not possible. 

So the question is: how does that initial "get height" method call initiate? Can you avoid that being called when the app is in the background? And have you deactivated background execution — or do you need it?

**Comment by hejiacong** [comment]
Thanks Daniel! I know what you mean,i can change my implements to solve this problem.
I submit this issue just want to known is there any unified solution,Thanks again.

**Comment by PrimaryFeather** [comment]
You're welcome!

There's no unified solution, but be sure to have a look at `SystemUtil.executeWhenApplicationIsActive()` — that will make it easy for you to guard those areas where background code may make stage3d calls.

Good luck! =)

**Comment by syberkitten** [comment]
We're still having this issue, and I'm not able to "guard: against it,
since nothing is actually happening on screen actively.

It's enough to have a GPU tile on screen, and the app crashes once it goes to background.

I've opened a query in the starling forum as well.

https://forum.starling-framework.org/topic/ios-app-crashes-as-soon-as-it-goes-to-background#post-118655

Please share ideas.... thanks

**Comment by syberkitten** [comment]
Wouldn't it be good to bake this safeguard into the starling internals
to make sure that no GPU access is happening if the app is not active?

I'm not talking about the Starling API but the internals which seem to cause
the  app to crash, as starling does not check if the application is Active
as far as i understand.

**Comment by PrimaryFeather** [comment]
I wrote some ideas I've got right in the [forum thread](
https://forum.starling-framework.org/topic/ios-app-crashes-as-soon-as-it-goes-to-background?replies=11#post-118676)!

---

For reference for readers who bump into this thread: first thing to do when you run into this on iOS is to completely stop Starling when it moves into the background; e.g. like this: 


Did you call `starling.stop(true)` when the app moves into the background? E.g. like this:

```as3
if (!SystemUtil.isDesktop)
{
    NativeApplication.nativeApplication.addEventListener(
        flash.events.Event.ACTIVATE, onActivate);
    NativeApplication.nativeApplication.addEventListener(
        flash.events.Event.DEACTIVATE, onDeactivate);
}

private function onActivate(e:*):void
{
    _starling.start();
}

private function onDeactivate(e:*):void
{
    _starling.stop(true);
}
```

**Comment by Adrian-S** [comment]
We started working with database and we have a lot of async calls.
Because of this we got an increase in #3768 errors, mainly on iOS.

@PrimaryFeather I was wondering if preventing this problem in the core of Starling is possible.

We are stopping starling on deactivate, but some of the async calls try to update the display tree and manage to call the Stage3D even with starling stopped. Most errors are from:
```
ConcreteTexture/dispose()
ConcreteRectangleTexture/upload()
VertexData/uploadToVertexBuffer()
```
... and maybe more.

I don't know if they can be deferred to a later time when the application is active again. But it would idiot proof the core.

`SystemUtil.executeWhenApplicationIsActive()` is sometimes useful, but sometimes invalidation system from FeathersUI is better.

**Comment by PrimaryFeather** [comment]
Hey Adrian,
you're absolutely right – ideally, this would be handled by Starling or AIR so that developers don't have to know or care about this stuff! 

However – at least with Starling's current architecture – this would mean that I'd have to put some kind of "guard" call around almost every call to Stage3D – because I can never know who calls a method, and if it that someone already took care of this runtime check. And even then, there would be cases I _cannot_ guard, because those methods return some kind of object _synchronously_ (e.g. think of `context.createRectangleTexture()` - what should that method do when the app is not active)?

So, this would (a) have quite a negative impact on performance and (b) still not take care of every issue. To handle this thoroughly, I'd probably have to wrap the Stage3D API on a low level and have _that_ API be used by Starling. Including wrappers for `RectangleTexture` and so on. 

Thus, my (hopefully) more pragmatic approach was to offer safe alternatives for most of the asynchronous calls that might lead to such a situation, e.g. using `Juggler.delayCall()` instead of a timer or deferring touch input to a time when the app is active. 

I understand that this can sometimes be tedious, like in your case with the asynchronous results from database calls. Very annoying stuff 🙄. But typically, there are only few limited "entry points" for those asynchronous calls that need to be guarded. If you can identify those, perhaps it's not as much of a problem as anticipated. 

I hope that this is at least a little help, Adrian!
