### ISSUE TITLE
Optimize setChildIndex for less objects creation

### ISSUE THREAD

**Issue by Fraggle** [Gamua/Starling-Framework#700]
Hello,

I noticed a lot of array beeing created by setChildIndex use of splice (especially from GAF).
From my personal tests, avoiding the 2 splices calls with this:
```
var offset:int = 0;
var size:int = mChildren.length;
sSortBuffer.length = size;
for (var i:int=0; i < size; ++i) {
 if ( i == oldIndex )  {
  ++offset;
  sSortBuffer[i] = mChildren[i + offset];
 } else if ( i == index ) {
  --offset;
  sSortBuffer[i] = child;
 } else {
  sSortBuffer[i] = mChildren[i + offset];
 }
}
sSortBuffer.length = 0;
```
Helped my framerate increase and memory decrease.

**Comment by b005t3r** [comment]
+1

**Comment by PrimaryFeather** [comment]
Definitely a good idea — thanks for bringing it up! I'll add that.

**Comment by neolit123** [comment]
fallthrough instead of an explicit branch:

```
switch(i) {
case index:
    --offset;
    sSortBuffer[i] = child;
    break;
case oldIndex:
    ++offset;
default:
    sSortBuffer[i] = mChildren[i + offset];
}
```

**Comment by Fraggle** [comment]
Just noticed a crash when the new index is equal or over the current size of children array. It happens when addChild() is called for an existing child.
So here is a fixed version:
```
var offset:int = 0;
var size:int = mChildren.length;

if ( index >= size )
 index = size - 1;

sSortBuffer.length = size;
for (var i:int=0; i < size; ++i) {
 switch(i) {
  case index:
    --offset;
    sSortBuffer[i] = child;
    break;
  case oldIndex:
    ++offset;
  default:
    sSortBuffer[i] = mChildren[i + offset];
 }
}
sSortBuffer.length = 0;

**Comment by Oldes** [comment]
+1

**Comment by PrimaryFeather** [comment]
I took this opportunity to have a look at "splice" in general, and to analyze the performance of Vector vs. Array. I created a custom implementation of "splice" and benchmarked it.

Here's the code:
https://gist.github.com/PrimaryFeather/6c4b7551478980a1e0ba

What I'd love to do is offer a "VectorUtil" or "ArrayUtil" class that contains a custom "splice" method. However, Vectors are tricky in AS3, because they are not really generics, but more or less a hack (IMHO). So I can't write a `splice` method that would work with, say `Vector.<String>` and `Vector.<DisplayObject>`. 

However, I could use `Object` as parameter type to pass the vector, like this:

```as3
public static function splice(array:Object, startIndex:int, deleteCount:uint=uint.MAX_VALUE,
                                        insertee:Object=null):void
```

However, this is much slower than a strictly typed parameter. Here are the benchmark results, executed on my 2007 iMac and iPhone 4S.

["5 x 1 mio" means: Iterating 1 million times over an array/vector with 5 elements, each time executing the same splice operations. The resulting numbers are milliseconds.]

```
## iMac, 5 x 1 mio
Utils.spliceObject → 1896
Utils.spliceArray → 1560
Utils.spliceVector → 1358
Array.splice → 5159

## iMac, 25 x 1 mio
Utils.spliceObject → 4105
Utils.spliceArray → 3063
Utils.spliceVector → 2584
Array.splice → 5280

## iMac, 100 x 250k
Utils.spliceObject → 2983
Utils.spliceArray → 2195
Utils.spliceVector → 1774
Array.splice → 1333

## iPhone 4S, 5 x 100k
Utils.spliceObject → 2151
Utils.spliceArray → 1067
Utils.spliceVector → 1138
Array.splice → 4469

## iPhone 4S, 25 x 100k
Utils.spliceObject → 3230
Utils.spliceArray → 2027
Utils.spliceVector → 2232
Array.splice → 4286

## iPhone 4S, 100 x 25k
Utils.spliceObject → 1788
Utils.spliceArray → 1396
Utils.spliceVector → 1630
Array.splice → 1032
``` 

You see that 'spliceObject' is slower than using a strictly typed parameter. However, for medium-sized vectors, the custom implementation is still faster than the native "Array.splice" method. And that doesn't take the temporary objects into account, which would probably be GC'ed some time later.

Even more interesting: "Array" is faster than "Vector" on iOS; on the Mac, it's the other way round. So I guess with AOT compilation, Array is faster than Vector! 

With that knowledge (that Vector is sometimes even slower than Array), and the not-quite-generic type problems, I'm actually considering not using "Vector" any longer in the future. I might replace all Vectors with Arrays in Starling 2.0. 

Short-term, though, I'll probably add a (private) splice method that takes `Vector.<DisplayObject>` instances and use that just in "DisplayObjectContainer".

Though I'd be happy about any comments. =)

**Comment by b005t3r** [comment]
Wait, so the original splice() is faster on your iP4 than this implementation? Why, how? Something has to be not quite right with this test I think.

And Vectors are faster in general than Arrays, even with your tests you can see a significant improvement, so I wouldn't really change everything to Arrays.

**Comment by PrimaryFeather** [comment]
> Wait, so the original splice() is faster on your iP4 than this implementation? Why, how? Something has to be not quite right with this test I think.

Only when the vector is long enough. With 5 objects and 25 objects, the new implementation is (much!) faster. Only with 100 objects, the original implementation is faster.

Actually, I'm surprised that the native implementation is not faster — it is native, after all. I thought the main reason why "splice" causes performance problems is that the GC has to clean up after it.

> And Vectors are faster in general than Arrays [...]

I thought that, too — but it is based on facts or just on hear-say? The tests above indicate that at least in AOT-compilation, Array is actually faster. And iOS is IMHO the most important target. 

I don't say that I've decided on really switching — but I consider it an option, because Arrays would allow subclassing and helper-methods that work around the limitation of the default API, whereas I can't do that with Vectors.

**Comment by b005t3r** [comment]
I did a test a while ago, with Arrays vs Vectors (I think it's still somewhere on Starling forums) and Vectors where slightly faster than Arrays. The test was pretty simple, I only measured how long does it take to iterate over Array/Vector, nothing else. I think Adobe's docs also advice you should use Vectors wherever possible, because they are faster.

I know there's a lot of different gossip around (like you should use linked lists, because they are faster - I did test and find the opposite to be true, to be honest), so I always try to test.

I really does surprise me that you got different numbers on your iMac and iP4s. This might be due to GC interrupting more often on mobile, so if you run all the test one by one in the same app garbage left by former tests might've slowed down the later ones (just a guess). I can't simply see how the internals/VMs would differ between desktop and mobile for a such simple scenario to make the difference even noticeable.

**Comment by Oldes** [comment]
I cannot understand how Vector can be slower than Array, because Vector is in theory just a raw block of memory with header describing a type and pointers (or direct values).

**Comment by b005t3r** [comment]
To be honest, I can't imagine how there can be any difference between these two (what Array has to exactly do to be slower?), but tests show that there's a difference :)

**Comment by PrimaryFeather** [comment]
> I did a test a while ago, with Arrays vs Vectors (I think it's still somewhere on Starling forums) and Vectors where slightly faster than Arrays.

You probably made that test with the AIR runtime, not the AOT compiler. The Vector *is* faster in JIT-mode.

Whatever the reason, my tests indicate that the performance benefit of Vectors does not translate to AOT compilation. I'd be happy about any confirmation or even being proven wrong — the exact code I used is in the gist referenced [above](https://gist.github.com/PrimaryFeather/6c4b7551478980a1e0ba).

**Comment by b005t3r** [comment]
Yes, I didn't test on iOS, but if things are that much different when using AOT compiler, clearly something has to be wrong with the compiler and I'm not sure if optimizing code for it is a good idea.

About the code you use, I don't think it's a good test. There's a log going on and you test using random numbers. I'd get rid of everything that's random, move all unnecessary method call's outside of tests, save the returned values and use these when measuring times. Currently the calls themselves can change your times quite significantly and with random values you don't test using the same scenarios for each method.

**Comment by PrimaryFeather** [comment]
You're right that random is not perfect for performance tests, but with one million repetitions, the difference is equalled out statistically. The result is the same each time I run the test, give or take a few ms. Logging is happening outside the time-measured parts.

But please, if you can find your old tests, it would be great if you could try them out on iOS!

> Yes, I didn't test on iOS, but if things are that much different when using AOT compiler, clearly something has to be wrong with the compiler and I'm not sure if optimizing code for it is a good idea.

It doesn't necessarily mean that something has gone wrong; it just works differently. In JIT compilation, you can optimize for the actual use case, while AOT requires the compiler to 'guess' how the code is going to be used. 

My guess is that AOT does not create implementations for Vector.<DisplayObject>, Vector.<String>, etc. — like a real "Generic" would require. Instead, it might fall back to (non-typesafe) Array mode, plus some overhead. But one way or the other, I find it highly unlikely that Adobe would change this behavior in the future. 

And the main point I've got with vectors is actually not only their performance: it's that they are hard to write generic code with. "splice" is flawed, and so are many other methods; but there's no way I can add new methods that work around those flaws. I could live with that if I knew it's sooooo much faster, but it isn't. It's only a little bit faster in JIT, and even slower in AOT. So why the heck use it? 

After all, I could make Starling *faster* than it is now (even with JIT) if I would consistently use Array and some helper methods.

**Comment by Fraggle** [comment]
I agree with you Daniel.
At first I went all out with Vectors because I like typed things, but I was duplicating stuff all the time because it's not a real generic.
I ended up removing most of my vector stuff and I went with arrays instead.

**Comment by b005t3r** [comment]
I don't have time currently to look for these test (still have a bug to fix and I'm going on vacation tomorrow), but they were really simple - just an iteration over Array/Vector. The differences were however slight in favor of Vectors (I think it was below 10%), so the  really question is how much are you going to gain or lose when switching to Arrays. Splice might be faster, but everything else could still be slower (or not :)

As for your tests, I'd at least move the unnecessary method calls outside of the part for which you measure the time - you have about 15 unnecessary calls for each iteration and only 5 you actually want to measure.

**Comment by PrimaryFeather** [comment]
Thanks, Sebastian — good to hear that I'm not the only one struggling with this. :smile: 

For now, I have added the optimized `splice` implementation just to the `DisplayObjectContainer` class. That solves the original issue, and should lead to a nice performance enhancement. 

The `Array` vs. `Vector` issue is still open for debate, of course. When I've got a little more time, I'll make a specific test that targets just the iteration and element access, just as you suggested, Łukasz.

In any case, thanks for all the comments so far! A very interesting discussion!! :+1:

**Comment by b005t3r** [comment]
I managed to find one simple test I did recently for comparing linked lists and Vectors performance. Vectors were slightly faster on desktop (Mac) and even more with mobile (Android) with this test, but maybe your results will be different:

https://gist.github.com/b005t3r/13621cf54c71db9f6e7c

**Comment by PrimaryFeather** [comment]
Thanks, Łukasz!

I'll close this thread, because the main issue has been solved. We can still continue to discuss any new findings on Array vs. Vector here, of course (or open up a separate issue).

**Comment by PrimaryFeather** [comment]
Now I had the time to make more basic Array vs. Vector tests, and the results are ... interesting. :wink: 

Here's the benchmark code:
https://gist.github.com/PrimaryFeather/9dd30ffb857d5fd0e0ad

This time, I focussed not on the "splice" implementation, but simply on accessing elements in a vector or array (get and set element at a certain index).

Here's the result on my two test devices:

```
## iPhone 4S, 256 x 100k
vector access (number) -> 2234
array access (number) -> 3137
vector access (string) -> 4511
array access (string) -> 3428

# MacBook Air, 256 x 1 mio
vector access (number) -> 1030
array access (number) -> 2596
vector access (string) -> 2100
array access (string) -> 3282
```

You can see that if we compare `Vector.<Number>` vs. `Array`, the vector always wins, no matter if we're in JIT or AOT mode (i.e. Flash Player or iOS).

However, if we use `Vector.<String>` instead, the results are different: now, the AOT version is faster. 

What to make of this? Maybe Adobe optimized the AOT version for primitive datatypes. That would mean that when you're storing any non-primitive data types, Vector is very useful (i.e. *always* faster), but for custom classes, not so much (because it might be faster or slower, depending on the platform).

But it remains to be seen if this result carries on to more data types (e.g. int, boolean, Object, custom classes).

**Comment by b005t3r** [comment]
Not sure what Adobe did to make accessing references slower than accessing primitives, but they had to do something :) And these differences are really big, 25%-33% (even more on Mac). Maybe it's a good idea to ask Adobe about this, because the only conclusion from these tests is: There's no proper way of storing data in a random access collection using AS3. 

My best guess is maybe (and that's a huge maybe) there's a some kind of automatic casting happening when you write a value to Vector and using AOT build and there's no such thing with Array?

**Comment by Oldes** [comment]
I already linked this thread with bugbase: https://bugbase.adobe.com/index.cfm?event=bug&id=3968894

**Comment by b005t3r** [comment]
:+1: Voted.

**Comment by PrimaryFeather** [comment]
Yes, it could be some kind of automatic cast. Although I tried to add some manual casts (`as String`) — but it made things only worse, for both Array and Vector.

But it gets even better! I just found another difference. I'm sure you remember that accessing Array or Vector elements is faster if you cast the argument to `int`, i.e. 

```as3
array[j] = array[numElements - 1 - j]; // slow
array[j] = array[int(numElements - 1 - j)]; // faster
```

That's why my Gist from above did just that. But I realized I only tested this in JIT, never in AOT. And guess what: In AOT mode, it's the other way round! The int-cast makes it much slower there. Here's a collection of all my results:

```
## iPhone 4S, 256 x 100k, with int-cast
vector access (number) -> 2123
array access (number) -> 3062
vector access (string) -> 4412
array access (string) -> 3417

## iPhone 4S, 256 x 100k, without int-cast
vector access (number) -> 1248
array access (number) -> 1663
vector access (string) -> 2718
array access (string) -> 2020

# MacBook Air, 256 x 1 mio, with int-cast
vector access (number) -> 1030
array access (number) -> 2596
vector access (string) -> 2100
array access (string) -> 3282

# Macbook Air, 256 x 1 mio, without int-cast
vector access (number) -> 1297
array access (number) -> 3052
vector access (string) -> 2451
array access (string) -> 3609
```

If you look at the iOS results, you'll see that the int-cast causes a significant performance degradation, much more so than the positive effect in JIT-mode. 

*sigh*. It's really hard to optimize any code if JIT and AOT results differ so much. :-/

**Comment by b005t3r** [comment]
This is the moment when I start to believe in all of these strange optimization stories like using linked lists instead of Arrays/Vectors.

**Comment by PrimaryFeather** [comment]
Haha, yes, I know what you mean ... :wink:

**Comment by Mishgan** [comment]
Hi, Daniel!  Thanks a lot for preventing extra memory allocations. 
I just wanted to mention that actually ```setChildIndex``` in ```DisplayObjectContainer``` could be in done more efficient way. Using two spliceChildren
 
```actionscript
spliceChildren(oldIndex, 1);
spliceChildren(index, 0, child);
```
 in the worst case requires 2 * numChildren steps ( moving from 0 to 1 index, eg ). We can improve it by the following solution :

```actionscript
const dir : int = _oldIdx < _newIdx ? 1 : -1;
for ( var i : int = _oldIdx; i != _newIdx; i+= dir ) {
     mChildren[i] = mChildren[i + dir];
}
mChildren[ _newIdx ] = child;
```
which requires just abs( index - oldIndex ) steps. So it will requires just ```numChildren``` steps in the worst case ( when we move child from 0 to numChildren-1 position or vice versa  ). Of course it is not general solution and can't be used in other functions, but maybe it would be reasonable to use it.

**Comment by PrimaryFeather** [comment]
You're right, that would be more efficient -- thanks for the suggestion! :+1: 
I'll maybe add that in the future, though it's probably not a super-high priority.

If anyone runs into performance problems with the current implementation, let me know, and I'll give this a higher priority!

**Comment by Oldes** [comment]
@Mishgan your code would fail in case, where child is already at tail of the display list and one call `addChild` to add child again to the same parent. (When `oldIndex` is for example 5 and `index` 6). Daniel's method works fine with such a case.

Anyway... I was checking usage of this `setChildIndex` function in my real project and it's very low (probably zero now, when I eliminated above scenario, where I was adding child, which was already added in the same parent). So I understand it's low priority for Daniel.
