### ISSUE TITLE
Strange results when using nested rendering to texture

### ISSUE THREAD

**Issue by b005t3r** [Gamua/Starling-Framework#717]
This is probably connected with #711 

I have a custom Sprite (BufferedSprite) which renders all its children to a RenderTexture an then display this texture using an Image instance (similar to what Filters do; it's a base class for other classes which would apply post-processing to such output texture before it's displayed).

If I use just one such Sprite, everything works fine. The problems start, when I put one BufferedSprite into another BufferedSprite.

Here's the demo project showing what's happening: https://dl.dropboxusercontent.com/u/23855128/BufferedRenderingTest.zip

**Comment by PrimaryFeather** [comment]
Okay, that was tricky. :wink:
The problem is that you do all the RenderTexture-Rendering with the "render" method, and that has some side effects.

First things first: here's a working version of the relevant class: [BufferedSprite](https://gist.github.com/anonymous/d7c81dfd28c042ee0f83)

This version splits up RenderTexture drawing and rendering in two methods (`onEnterFrame` and `render`, respectively). That avoids any problems.

Now to the details. The RenderTexture class has its own "RenderSupport" instance. That makes sense, because you want to be able to draw to the RenderTexture anytime, e.g. in a touch or enter frame event handler. If you needed to pass a "RenderSupport" instance to the draw method, you could *only* draw inside `render` methods.

But there's a problem. Inside the `draw` method, the following happens (simplified):

```as3
mSupport.renderTarget = mActiveTexture;
mHelperImage.render();
mSupport.renderTarget = null;
```

In a perfect world, it should look like this, though:

```as3
var origRenderTarget = mSupport.renderTarget;
mSupport.renderTarget = mActiveTexture;
mHelperImage.render();
mSupport.renderTarget = origRenderTarget;
```

That way, we could restore the render target that was active when we entered the method. However, that doesn't work! :scream: That's because "mSupport" is the one from the RenderTexture, not the one that's used by Starling during the render loop. So it actually doesn't contain the current render target (but just `null`).

To prove the case, I made a quick test and added a property on "RenderTexture" that allows to provide the previous render target. Veeery ugly, but that fixed the problem. 

In any case: for the time being, the recommendation is: don't draw to RenderTextures from within "render" methods. And in your case, that fix is referenced above.

Please try it out — my guess is that this also fixes your Feathers problem, if you used the "BufferedSprite" there as well.

**Comment by b005t3r** [comment]
OK, I'll give it a try, but there's one, not so small, problem with splitting the rendering step in two (I did think about it before putting everything inside ```render()```) - your ```Event.ENTER_FRAME``` handler might be called before another handler, which would alter ```BufferedSprite```'s contents (e.g. ```Tween```). 

This way you're always one frame behind when rendering things to the screen plus you can't really render ```BufferedSprite``` instance to texture without adding it to ```Stage``` and waiting for one frame to render (and this is basically what my app is supposed to do :) ) I probably can add some kind of a workaround (like a ```validate()``` method) to handle this scenario, but still this is not the way I'd prefer to do it.

As for the ```RenderSupport``` it would be great to have something like a stack of render targets - like the one we have for matrices - you would probably have to make it global and common for all ```RenderSupport``` instances.

**Comment by PrimaryFeather** [comment]
> Your Event.ENTER_FRAME handler might be called before another handler, which would alter BufferedSprite's contents.

Yes, that's true. I can't think of a very elegant workaround for this problem, either ... 
One thing you can do is let your "root" object override "render" and dispatch a custom event (like "Event.RENDER") before calling "super.render()". Then you could listen to that event in your BufferedSprite instead of "ENTER_FRAME". 

That way, you'd always execute after the other "ENTER_FRAME" events and before the rest of the rendering takes place.

To make this simpler, I could dispatch "Event.RENDER" in Starling.as, right before starting rendering. That might not be a bad idea.

> As for the RenderSupport it would be great to have something like a stack of render targets - like the one we have for matrices - you would probably have to make it global and common for all RenderSupport instances.

"global" and "common" are the two words that I don't like in this sentence. :wink:

**Comment by b005t3r** [comment]
> To make this simpler, I could dispatch "Event.RENDER" in Starling.as, right before starting rendering. That might not be a bad idea.

Great minds think alike, I guess, because that's the exact thing I wanted to suggest :) I just wasn't sure if this won't hurt the performance (I think firing an event nobody listens to is quite cheap, though), but it would made creating a custom rendering code much easier.
Also one thing I'm not sure about is how would this work when rendering to a texture and the object being rendered is not added to Stage?

> "global" and "common" are the two words that I don't like in this sentence.

Yeah, me too :) But it's a thing to think about. Stage3D does only support one global Context3D and Starling tries to "hide it" with multiple RenderSupport instances - most of the time it works quite nice, but sometimes things get messy (like with the render targets).

**Comment by PrimaryFeather** [comment]
I just added that new Event and tested it with your code — seemed to work nicely! :smile: 
Performance is not affected, since I'm only dispatching it on the Starling instance, not on the display list. That should be a clean solution!

As for the context vs. the render support instances: I'm aware of the problem and will keep it in mind! 
BTW, please also let me know if this fixes your original problem with the Feathers-project.

**Comment by b005t3r** [comment]
OK, thanks. And what about rendering to a texture? My display object won't get this event while being rendered to a texture, right?

**Comment by PrimaryFeather** [comment]
No, that event is only dispatched when the complete display list (i.e. the stage) is rendered.

**Comment by b005t3r** [comment]
So still it's kind of a workaround which needs another workaround, don't you think? It would be much more convenient to have a display object which doesn't need any special steps to be done when being rendered to a texture. Also, the scenario I mentioned earlier with BufferedSprite being a child of another BufferedSprite, won't work at all when the first one is rendered to a texture.

**Comment by PrimaryFeather** [comment]
I think I'm missing the problem right now — the BufferedSprite I linked above does work fine in your sample project, by simply replacing "Event.ENTER_FRAME" by "Event.RENDER". At least in my tests — am I missing something? Why would you need such an Event for rendering to a texture?

**Comment by PrimaryFeather** [comment]
(And yes, I'd also prefer it if you could do whatever you want in a render method, but for now we'll have to live with that limitation.)

**Comment by b005t3r** [comment]
Yes, but consider this scenario:

A BufferedSprite has another BufferedSprite added as a child object. I need to render the first one to texture (or bitmap data, that's what the app I'm currently working on is supposed to do). If relying only on Event.RENDER there's no way to make it work - none will be updated before rendering. I can add a validate() method to BufferedSprite and call it before rendering to a texture, but this will not validate the inner BufferedSprite (to do it I'd have to go recursively through all children and look for any BufferedSprite instances; and do the same for their children, etc.).

When I think about it now, there's also a similar problem as when using Event.ENTER_FRAME - if these two BufferedSprites register for Event.RENDER, there's no way to make sure they are validated in the right order (if the child validates after the parent, it's basically the same scenario as with Event.ENTER_FRAME - rendering is one frame behind).

Unless I'm really missing something this seems not to be a solution after all :/

**Comment by PrimaryFeather** [comment]
No, sorry, I still don't get it. :grimacing: 
In your "BufferedSprite in BufferedSprite" scenario, there are three steps happening in each frame:

1) the children of the sprites are updated (i.e. change position, tween, etc.). Happening probably via some "TOUCH" or "ENTER_FRAME" logic (including Juggler stuff).
2) Before Starling renders the display list, it dispatches "Event.RENDER". Now, your buffered sprites created their textures; first the inner one, than the parent.
3) Now the "render" method of the outer (and then, the inner) BufferedSprite is called, which draw the images with the buffer-textures.

Where's the problem? (Again, your demo works fine, and it has nested BufferedSprites.)

**Comment by b005t3r** [comment]
> 2) Before Starling renders the display list, it dispatches "Event.RENDER". Now, your buffered sprites created their textures; first the inner one, than the parent.

But this is not guaranteed. The parent's texture needs the child's texture to be updated first (because it will be rendered to parent's texture), but they both register for the event independently - the parent might as well register before the child and when validating (handling the event) it will use child's contents rendered one frame ago.

**Comment by PrimaryFeather** [comment]
Ah, heureka, now I see the problem, too. :bulb: 
Damn, yes, that's right. :poop:

*Thinking*.

**Comment by b005t3r** [comment]
Maybe you'll come up with something better, but changing RenderSupport's internals so they would all use one global render target (a static member) doesn't seem that bad to me. It is a bit hardcore, but all would be hidden from the client code by the RenderSupport. From the client's perspective you'd simply have to check what the current RenderTarget is, store it in a local variable if you want to change it and reassign it once you're done - just like with matrices, masks, etc.

**Comment by PrimaryFeather** [comment]
What I don't like with that approach is that the RenderSupport object is actually not very useful when accessed *outside* a render method. It contains lots of data that simply makes sense only in the render loop, e.g. the matrices. To expose the whole object just to be able to access the render target ... that somehow doesn't seem to be correct to me.

What we really need would be a getter for the render target on the "context" object (which is global anyway), but I'd have to create a wrapper for all of it's methods, then (I can't create a subclass). Definitely not an option for the 1.x branch; but something to consider for 2.x — that would make some things a little easier.

For now, I can only offer another workaround: in the "RENDER" callback, iterate over the BufferedSprite's parents to find out if it's part of another (enabled) one. In that case, act as if `_bufferingEnabled` was `false`. That way, in such a case, the complete object hierarchy below the outermost BufferedSprite will be rendered together. And without any nesting of BufferedSprites, the problem will go away.

Sorry that I can't offer any other solution right now — but you definitely got me thinking about some parts of Starling 2.0.

**Comment by b005t3r** [comment]
> For now, I can only offer another workaround: in the "RENDER" callback, iterate over the BufferedSprite's parents to find out if it's part of another (enabled) one. In that case, act as if _bufferingEnabled was false. That way, in such a case, the complete object hierarchy below the outermost BufferedSprite will be rendered together. And without any nesting of BufferedSprites, the problem will go away.

I can't really use this approach, I need the children and the parent to use their inner textures (which I use for postprocessing effects).

> What I don't like with that approach is that the RenderSupport object is actually not very useful when accessed outside a render method. It contains lots of data that simply makes sense only in the render loop, e.g. the matrices. To expose the whole object just to be able to access the render target ... that somehow doesn't seem to be correct to me.

I didn't suggest anything like that. Nothing would change, really - RenderSupport would still be used as it is now (in DisplayObjects' render() method and internally by RenderTexture instances). One thing what would change is the currently set render target in a newly allocated RenderSupport instance - currently it's always null, no matter if what's set in Context3D. After making render target static (common to all instances) it would be the currently set render target (null if rendering to screen, or a texture reference, if rendering to a texture).

Currently the code responsible for RenderTexture rendering looks like this:

```as3
mSupport.pushClipRect(sClipRect);
mSupport.setRenderTarget(mActiveTexture, antiAliasing);
if (isDoubleBuffered || !isPersistent || !mBufferReady)
    mSupport.clear();
// draw buffer
if (isDoubleBuffered && mBufferReady)
    mHelperImage.render(mSupport, 1.0);
else
    mBufferReady = true;
try
{
    mDrawing = true;
    execute(renderBlock, object, matrix, alpha);
}
finally
{
    mDrawing = false;
    mSupport.finishQuadBatch();
    mSupport.nextFrame();
    mSupport.renderTarget = null;
    mSupport.popClipRect();
}
```

After making the change you could to this:

```as3
var oldRenderTarget:Texture = mSupport.renderTarget;

mSupport.pushClipRect(sClipRect);
mSupport.setRenderTarget(mActiveTexture, antiAliasing);
if (isDoubleBuffered || !isPersistent || !mBufferReady)
    mSupport.clear();
// draw buffer
if (isDoubleBuffered && mBufferReady)
    mHelperImage.render(mSupport, 1.0);
else
    mBufferReady = true;
try
{
    mDrawing = true;
    execute(renderBlock, object, matrix, alpha);
}
finally
{
    mDrawing = false;
    mSupport.finishQuadBatch();
    mSupport.nextFrame();
    mSupport.renderTarget = oldRenderTarget;
    mSupport.popClipRect();
}```

The only thing needed to make it work would be this (in RenderSupport.as):

```as3
private var mRenderTarget:Texture;
```
to
```as3
private static var mRenderTarget:Texture;
```

I think it's pretty harmless, makes custom rendering (like mine) possible and it's actually safer than the current solution, where you always assume that the previously set render target was the backbuffer. Please think about it, Daniel.

**Comment by PrimaryFeather** [comment]
You're forgetting that there could be several Starling instances. Thus, a static member variable can't be used (the different Starling instances would run into conflicts). Instead, I'd need to add something like this:

```as3
Starling.current.renderSupport.renderTarget;
// or
Starling.current.renderTarget;
```

The first line is the one I was talking about in my last post (I'm not very happy with that), and the second one is a hack, because what we're really after is this:

```as3
Starling.current.context.renderTarget;
```

That would be the optimal solution, because the context is where this information belongs. But that's not possible without major changes (as described above).

I don't say that the upper two solutions are not possible, I just don't like them very much. But if this is a show stopper for you ... I'll keep investigating.

**Comment by b005t3r** [comment]
> I don't say that the upper two solutions are not possible, I just don't like them very much. But if this is a show stopper for you ... I'll keep investigating.

Yeah, it is. Of course, I can work around anything, but it would require a lot w (in my opinion) unnecessary code.

But if the render target has to be bound with the Starling instance, why not do it, like you suggested:

```as3
Starling.current.renderTarget;
```

It had to be an internal member accessed only by RenderSupport, but other than that - a clean fix in my opinion. I'm aware that the real problem is how Context3D API looks like, but wrapping its every method in another object just for making accessing this one member possible doesn't seem all that great as well.

**Comment by PrimaryFeather** [comment]
<blockquote>I'm aware that the real problem is how Context3D API looks like, but wrapping its every method in another object just for making accessing this one member possible doesn't seem all that great as well.</blockquote>

It's not just that — there are several other properties (e.g. scissor rectangle and back buffer size) that cause similar issues. 

But don't worry, I see your point, and I agree that an (internal) property wouldn't hurt much. I'll get back to you on this.

**Comment by PrimaryFeather** [comment]
I think that should do it!

I realized that there had already been a similar problem: shader programs. They are also stored on the context, and I needed to remember which one have been uploaded, etc. For this, I introduced "Starling.current.contextData", a Dictionary.

And this is where I now store the render target, as well. Any call to "RenderSupport.renderTarget" now accesses this dictionary.

I tested it with your original sample code, and that worked.
Please try it out and tell me you're happy! :wink:

**Comment by b005t3r** [comment]
Ha, sounds like a solution to me :) Thanks!

I'll give it a try and let you know if everything works.

**Comment by b005t3r** [comment]
OK, I tested the changes you made on my machine and here are the results:
- nested rendering to texture works fine (tested with this examples: https://dl.dropboxusercontent.com/u/23855128/BufferedRenderingTest.zip)
- drop shadow filters and clip rect combination works fine (https://dl.dropboxusercontent.com/u/23855128/ClipRectTest.zip)
- using drop shadow filter with Feathers *does not* work - some shadows are clipped (https://dl.dropboxusercontent.com/u/23855128/ClipRectFeathersTest.zip)

So there's still one problem left.

**Comment by PrimaryFeather** [comment]
Okay, thanks for the update! I'll look into it.

**Comment by b005t3r** [comment]
I think this might be a Feathers problem. I tried using a clip rect combo in my other app (a child object had its clip rect set, its parent was rendering to a texture while being a child of a Feathers ScrollContainer) and had a really strange results, from, depending on the current scrolling, object not being drawn at all to being only partially visible. Plus the parent object (which renders to a texture in its render() method - similarly to BufferedSprite) was not clipped by ScrollContainer's clip rect.

**Comment by PrimaryFeather** [comment]
Unfortunately, I didn't manage to squeeze it in before my upcoming vacation. I'll look into it when I'm back. Except if, maybe, @joshtynjala, you want to give it a quick shot? Perhaps you can isolate the issue, i.e. find where exactly Starling is doing wrong?

**Comment by joshtynjala** [comment]
I'm pretty swamped with finishing up Feathers 2.2 and the Feathers SDK. If I get a moment, though, I'll try to take a look.

**Comment by PrimaryFeather** [comment]
No worries, Josh! If it doesn't fit in, I'll look at it when I'm back. Your other tasks should definitely be the priority.

@b005t3r, I hope you can live with 2-3 more weeks delay!

**Comment by b005t3r** [comment]
I'll try :)
