### ISSUE TITLE
Existent a problem in mask touch event

### ISSUE THREAD

**Issue by wenguoqing** [Gamua/Starling-Framework#744]
public function hitTest(localPoint:Point, forTouch:Boolean=false):DisplayObject
        {
            // on a touch test, invisible or untouchable objects cause the test to fail
            if (forTouch && (!mVisible || !mTouchable)) return null;
	    
           if (mMask && !hitTestMask(localPoint))return null;

            // otherwise, check bounding box
            if (getBounds(this, sHelperRect).containsPoint(localPoint))return this;
            else return null;
        }
localPoint equal to DisplayObjectContainer.sHelperPoint a static variable
if mMask is DisplayObjectContainer,DisplayObjectContainer.sHelperPoint has been modified in a function hitTestMask,localPoint has been modified.

        public function hitTest(localPoint:Point, forTouch:Boolean=false):DisplayObject
        {
            // on a touch test, invisible or untouchable objects cause the test to fail
            if (forTouch && (!mVisible || !mTouchable)) return null;
			//if (mMask && !hitTestMask(localPoint))return null;
			//guoqing.wen Modify this mask mouse event 
            if (mMask)
			{
				sHelperMaskPoint.copyFrom(localPoint);
				if (hitTestMask(localPoint))localPoint = sHelperMaskPoint;
				else return null; // if we've got a mask and the hit occurs outside, fail
			} 
            // otherwise, check bounding box
            if (getBounds(this, sHelperRect).containsPoint(localPoint))return this;
            else return null;
        }

Also the existence of a problem, if mMask internal the existence of mask,sHelperMaskPoint a static variable has been modified in a function hitTestMask.But this is almost non-existent

**Comment by PrimaryFeather** [comment]
Thanks a lot for the heads-up, that's a good catch! 

I think my fix should solve the problem in all circumstances. The problem with the "hitTestMask" method is that, just as you pointed out, the method may be called recursively. In that case, no number of static helper variables will do the trick.

But since a mask object that contains a mask itself will be very rare, it's probably justifiable to simply create a local point for this case.

Nevertheless, this recursiveness is giving me headaches, so I'd appreciate it if you could look over my fix yourself and find out if you think there could be any more trouble. :wink:

Thanks again!
