### ISSUE TITLE
Feature Request: mask can be cache,like filter

### ISSUE THREAD

**Issue by hejiacong** [Gamua/Starling-Framework#752]
one mask need 2 draw call，and can not batch,if too many mask object in same view,it cause frame rate down,the performance not as good as PixelMask in static mode,because PixelMask only need to render a Image with RenderTexture after create.so i think mask can do like PixelMask,or like filter,can be cache when the mask not change offen

**Comment by PrimaryFeather** [comment]
If I understand you correctly, what you're suggesting would be another masking mode that works just like the PixelMask extension, i.e. using a RenderTexture instead of the stencil buffer. 

You're right, if the mask is static, this would have the advantage of only requiring one draw call, at the cost of the additional texture memory. Which does make sense in some cases.

That's definitely an interesting idea, and I'll consider this! Thanks a lot for the suggestion!

**Comment by hejiacong** [comment]
Yes,That is what i mean

**Comment by PrimaryFeather** [comment]
In Starling 2, there's now a rather simple way to make that happen, using the `cache()` feature of `FragmentFilters`.

```as3
var sprite:Sprite = new Sprite();
var maskee:Sprite = ...; // the object that needs to be masked
var maskee.mask = canvas; // let's say canvas creates the mask
sprite.addChild(maskee);

sprite.filter = new FragmentFilter();
sprite.filter.cache();
```

This will cache the complete, masked object into a texture and render that instead. The only caveat is that you actually have to wrap the masked object in a Sprite, and add the filter to that sprite. 

In any case: the gist of this is that a plain "FragmentFilter", in combination with "cache()", now allows you to cache anything as a texture. It's a replacement for "cacheAsBitmap", if you will.

Thus, I will close this issue for now, since I think this is a feasible workaround.
