### ISSUE TITLE
Flattening FragmentFilter cache causes QuadBatch to dispose texture in use?

### ISSUE THREAD

**Issue by vroad** [Gamua/Starling-Framework#759]
I only confirmed this problem with my ported starling 1.7, but this should happen with original version.
Finally I found out that QuadBatch was dispoing cached texture. FragmentFilter returns cached QuadBatch instance if it already has cache created before flattening, and QuadBatch disposes it even though it's still owned by FragmentFilter.

https://github.com/Gamua/Starling-Framework/blob/v1.7/starling/src/starling/filters/FragmentFilter.as#L548

I tried turning off `QuadBatch.ownsTexture` property and the problem seems gone.

https://github.com/vroad/starling-openfl/commit/e440b23948d87b8330c5d598abd28e5b1d065294

**Comment by PrimaryFeather** [comment]
Hm, I changed some of this logic with version 1.7, because there were situations which could cause memory leaks.

Could you describe the problem in a little more detail, maybe with a sample project / sample source code? I'm not 100% sure I know how to reproduce it from your description alone.

Thanks in advance!

**Comment by vroad** [comment]
I've managed to reproduce the same bug with FilterScene sample from official Starling 1.7. I just needed to call unflatten() after flattened contents are created.
This code causes an error: "Error: Error #3663: Sampler 0 binds an undefined texture."

https://gist.github.com/vroad/1852d8edbeb9ce4c21ad#file-filterscene-as-L59

**Comment by PrimaryFeather** [comment]
That should do it! Your sample runs fine now. :smile:

**Comment by vroad** [comment]
New code creates new texture even if filtered result is already cached. That will increase memory usage and cause cached result to update.

Could you take texture from cache if it's already cached and set "QuadBatch.ownsTexture = false" as I shown in my code?
Also in my code, I'm trying to store the result in cache if cache is requested and not yet created.

This should be safe unless you manually dispose filter before unflattening.

**Comment by PrimaryFeather** [comment]
The problem with setting `QuadBatch.ownsTexture = false` is that it will cause a memory leak in other situations (see #726). That was the reason I added the "ownsTexture" property in the first place.

Thus, I had to use this compromise, since it's the only solution I see that avoids both problems (memory leak vs. lost texture).
