### ISSUE TITLE
Feature requests for Starling 2.0

### ISSUE THREAD

**Issue by GRIM2D** [Gamua/Starling-Framework#773]
Hello, I really love Adobe Air and Starling. Starling is easy to use, simple and fast framework.
But, unfortunately, in some games, where I need to control over 5000 objects (only Starling, no physics engine), starling becomes a bit slower. I get stable ~30fps. And I ported my game to SpriteKit. I'm currently using SpriteKit the first time. I would like to see some of advantages of it and my requests in Starling in future versions.

1. By default, touch handler is disabled.
2. Calling functions instead of dispatching events:
for example
```actionscript
class MySprite extends Sprite {
override public function touchBegan(touches:Vector.<Touch>):void {...}
override public function touchMoved(touches:Vector.<Touch>):void {...}
override public function touchEnded(touches:Vector.<Touch>):void {...}
override public function enterFrame(time:int):void {... }
override public function addedToStage(parent:DisplayObject):void {...}
...
```
or using interfaces
```actionscript
interface ITouchCalls {
function get touchable():Boolean;
function touchBegan(touches:Vector.<Touch>):void;
function touchMoved(touches:Vector.<Touch>):void;
function touchEnd(touches:Vector.<Touch>):void;
}

interface IRenderCalls {
function enterFrame(time:int):void;
}

interface IStageCalls {
function addedToStage(parent:DisplayObject):void;
function removedFromStage():void;
}
```

I think using interfaces makes  objects more flexible and customizable. So I can add only functions that I use.

```actionscript
class PlayButton extends Image implements ITouchCalls { ... }
class Enemy extends Image implements IStageCalls, IRenderCalls { ... }
```
3 . `addChild()` must throw error if displayobject has a parent. For sorting the hierarchy use `zIndex`
4 . Default settings architecture:
```actionscript
class TextureMipMapping {
static const DEFAULT:int = -1;
static const FALSE: 0;
static const TRUE:int = 1;
}

class TextureScale {
static const DEFAULT:Number = Number.NaN;
}
```
```actionscript
...
//Setting default variables
Starling.TextureMipMap = TextureMipMapping.FALSE;
Starling.TextureScale = 3.0;
starling = new Starling(...);
...

//Image texture has no mip and scaled to 1/3;
var image = new Image(Texture.fromEmbeddedAsset(SomeClass));

//image2 texture has no mip and scaled to 1/2;
var image2 = new Image(Texture.fromEmbeddedAsset(SomeClass, TextureMipMapping.DEFAULT, 2));

//image3 texture has mip and scaled to 1/3
var image3 = new Image(Texture.fromEmbeddedAsset(SomeClass, TextureMipMapping.TRUE, TextureScale.DEFAULT));
```

**Comment by PrimaryFeather** [comment]
Thanks a lot for your comments, and for the nice words about Starling! It's great to have somebody around who's using both Sprite Kit and Starling! :smile:

1 + 2: Concerning methods + interfaces instead of events for ENTER_FRAME and TOUCH: while I'd like the idea of having such methods, this is an area where I'd like to keep with the Flash methodology. The original goal of Starling was to provide something that's extremely similar to the Flash API, but renders much faster. I know I changed some things here and there when I didn't like something in the original API or when the GPU-based architecture called for it; but events are such an important part of Flash that I'd like to keep them that way. 

At least for the "ENTER_FRAME" events, performance is not an issue any longer, as I optimized that implementation. The hit-tests for touch events are an issue, though, and I'll consider a change concerning the defaults here. 

3. I wouldn't like to change that; I actually consider that a feature. :wink: If you add an object that already has a parent to another object, it will be removed from its former parent automatically. This also means that you can quickly change the index of a child by calling ```parent.addChildAt(object, newIndex)```.

4. I didn't know about that — an interesting idea! I'll definitely consider that! Would be cool to just be able to change defaults to your liking, anytime. 

So, again, thanks a lot for the suggestions! If you run across anything else (even small things), don't hesitate to tell me about it.

Daniel

**Comment by kaikoga** [comment]
@GRIM2D FYI, I came up to this thread and just want to share some of my knowledge:

I'm aware, as you, that touch events are some sort of handy but slow if you have much many objects. While touch events are excellent and kind of less mixing up things for situations like a couple of UI buttons, many times when I have really many objects I come up to just catch the touch event at the root ```Sprite```, disable ```touchable``` with ```false``` for everything except that (which effectively disables the touch handlers of every child object) , and do the hit test in game logic with given touch location. That'll bypass the whole event system and make your games faster! :) Things like ```ADDED_TO_STAGE``` could also be entirely bypassed for massive objects by not adding anything to stage but manually using ```QuadBatch.addImage()``` to draw something, and I'm personally fairly satisfied with the performance I get.

Therefore, in my thoughts I think Starling has no problems in architecture most of the time when it comes to performance, for you can easily alter how hit testing and rendering are done at more game-logic-and-Stage3D-friendly level when you actually have to.

**Comment by zenrobin** [comment]
Excited about 2.0.  We love Starling :)

Some feature requests: 
+ Optimization tools that fill the gap between the profiler and Scout and Starling. For example, flatten and drawBatch (?) can be great speedups. But if used incorrectly they can slow things down or cause confusion (especially flatten).  If Starling can "detect" when a sprite is never changing, or when a sprite changes too much, it could generate a report that lists it as a candidate for optimizing 
<this way>.

+ Dynamic Light Support (faked) to help augment the particle system and Sprite3D -- the sexy side of Starling. 

+ Gestouch + Touch  -- we use Gestouch, a fantastic, but old-ish touch library because it gives us more control and more gesture options. Consider integrating, or augmenting Touch offer more of what Gestouch offers.

+ Worker Thread Integration - If Starling could automatically make use of worker threads for common tasks, or if Starling could make it easier for end users to incorporate worker threads, that would be awesome.

+ Integrated Video support via Video Texture.  It's not that hard to setup a video texture class using Adobe's instructions. And not that hard to use Feather's video player.  But there are all sorts of conditions that you have to cover -- limits to how many videos that can be on screen at once, buffering and loading states, cleanup code (not easy), etc.   Wouldn't it be nice to have a Starling class called VideoSprite that just worked?  addChild(new VideoSprite("http://myvideo.mp4));  And you're done.  Well, some configuration might be needed....     But then you can add it as a Sprite3D object and have the video spin around or be placed as a billboard in perspective, and/and/and.... 

Yeah, that last one about video is a bit much for a "framework." But maybe it makes the other feature requests look better :) 

Thanks for reading.

**Comment by PrimaryFeather** [comment]
Thanks a lot for the additional comments, guys! :smile:

@kaikoga That's definitely a smart way to do it, yes! If you need more optimized touch handling, disable touch events at a certain level and just use "hitTest" or custom code to process the touch input. Performance-wise, that's the best you can do.

@zenrobin Here are my comments about those ideas:

(1) Agreed, especially "flatten" is often misunderstood, because people think it will always be a good idea to call it — while it can make rendering slower, too, when not used appropriately. What I will look into in a future version will be to automatically detect if something has changed since the last frame, so that I can maybe reuse some of the buffers. That would make "flatten" more or less obsolete. That won't be part of the 2.0 release (I need to set myself some limits, otherwise it will never come out \*g\*), but a later one.

(2) That's planned! I want to add support for Andreas Löw's [Sprite Illuminator](https://www.codeandweb.com/spriteilluminator) in Starling 2.0 (as an extension).

(3) The gist of this would be that you'd like some high level gestures that you can listen for, right? So that you don't need to work directly with TouchEvents for things like a swipe?

(4) I'd like to look into this in a future release, yes — especially for the AssetManger, it would be helpful. Again, not in 2.0, though.

(5) I've seen in the forum that video textures are a constant source of frustration. I guess I'll have to create my own project with videos to see where exactly the main pain points are (besides bugs in AIR). Then I could maybe come up with something. But this would be a good candidate for an extension, it doesn't have to be part of core Starling, probably (as you said yourself). 

Again, thanks for all the input, that really helps! :smile:

**Comment by b005t3r** [comment]
Here's a couple of my ideas. Not sure if all (or any) of them are any good.

1. **Batching** Currently display objects are put into a single batch up to a point when something (state) changes - a texture, shaders or blend mode - and a new batch is prepared for the new set of parameters and the old one gets rendered. And when it changes again, another one gets in and the previous one is rendered, etc. My idea is to batch objects even when things like texture, shader or blend mode change - a new batch would be started only if vertex format changes between objects (or vertex format's size, to be precise), so vertex and index data is uploaded to GPU less often. Of course this means batches would have to be split into smaller sub-batches for which parameters would differ and ```drawTriangles()``` would have to be called only for a part of the uploaded vertices and indices vectors. I believe this + changing only the parameters which actually change (texture, shaders, blend mode) from one batch to another would make things render even faster. 

2. **Batching of flattened objects** I'd like to be able to batch flattened Sprites just like I do with e.g. TextFields (when ```batchable``` property is set to ```true```). I also think it's a good idea, when flattening a Sprite, to reuse ```mFlattenedContents``` of its children if they've been flattened as well. Flattened parent Sprites should also detect (listen to an event) when their children change (e.g. flatten or unflatten) and recache its contents before being rendered.

3. **Overriding ```BlendMode.AUTO``` when flattening** This is probably something that is going to change entirely, but I'll write it anyway :) When flattening a Sprite its children with ```blendMode``` set to ```AUTO``` are batched separately. It would be convenient to be able to override this behavior by passing an additional parameter to ```flatten()``` method, so less batches is created.

4. **Pixel perfect rendering** It's quite a pain currently, if I'm honest, to make it work, mostly because you have to do in every display object, on every objects' hierarchy level, to be sure everything will render properly (not on sub-pixels). But internally it's actually a feature that's really easy to add. Just make it possible to create a ```QuadBatch``` (or some other kind of batch in 2.0) which, when another ```Quad``` or ```QuadBatch``` is added to it, will call ```Math.round()``` on every vertex's position (in the current version two lines of ```VertexData``` have to be changed in ```copyTransformedTo()``` method). Then Starling (or ```RenderSupport``` instance it's using) could use such batch to make everything render in a pixel perfect fashion. Of course, this should be optional (a property should be added to ```Starling``` class).

5. **```getBounds()``` optimization** For complex custom display objects I often override ```getBounds()```, so cost of calling it is considerably lower (and it gets called a lot). The implementation is always the same:
```as3
override public function getBounds(targetSpace:DisplayObject, resultRect:Rectangle = null):Rectangle {
    if (resultRect == null) resultRect = new Rectangle();
    // optimization
    if(targetSpace == this) {
        resultRect.setTo(0.0, 0.0, WIDTH, HEIGHT);
    }
    // optimization
    else if(targetSpace == parent && rotation == 0.0) {
        var scaleX:Number = this.scaleX;
        var scaleY:Number = this.scaleY;
        resultRect.setTo(
            x - pivotX * scaleX,
            y - pivotY * scaleY,
            HEIGHT * scaleX,
            WIDTH * scaleY
        );
        if (scaleX < 0) { resultRect.width  *= -1; resultRect.x -= resultRect.width;  }
        if (scaleY < 0) { resultRect.height *= -1; resultRect.y -= resultRect.height; }
    }
    else {
        getTransformationMatrix(targetSpace, helperMatrix);
        GeomUtil.transformPoint2D(helperMatrix, 0, 0, helperPointA);
        GeomUtil.transformPoint2D(helperMatrix, WIDTH, HEIGHT, helperPointB);
        resultRect.setTo(
            helperPointA.x < helperPointB.x ? helperPointA.x : helperPointB.x,
            helperPointA.y < helperPointB.y ? helperPointA.y : helperPointB.y,
            Math.abs(helperPointA.x - helperPointB.x),
            Math.abs(helperPointA.y - helperPointB.y)
        );
    }
    return resultRect;
}
```
so it would be great to have a static method somewhere is ```starling.util``` which I could call instead of copying the code or, even better, ```Sprite``` could work in two modes - default one iterating through all the children to calculate bounds and a new one where it would use given width and height.

6. **Scale3Image-like objects moved to Starling from Feathers** This is a minor thing really, but I often have to import feathers just to use these classes (which are really, really useful, btw) and I think they should be made a part of Starling.

OK, that's it :) I know a lot is going to change in Starling 2.0, so please at least threat these things I wrote as something to keep in mind :)

**Comment by PrimaryFeather** [comment]
Thanks for taking the time to write down those great ideas, Łukasz! I'll add my comments below.

1) I understand what you mean, an I'll think about that! In my current implementation, batching works similar to before, but I've seen the thread in the forum mentioning this adaptation, and maybe that can be done.

2) If you've got a flattened sprite, batching that again wouldn't be much different from not flattening at all, performance wise. Only if you've got a very deep and complex object structure (deep hierarchy) would that make a difference. However, you will get an alternative to flattening that's much more flexible, anyway — so you'll be able to do that.

3) Noted!

4) You're right, that has to be tackled, as well. I agree that this is very painful right now.

5) I wasn't aware of this problem — thanks for the heads-up! I'll see what I can do to make this easier.

6) Scale3 and Scale9 functionality will become part of the core, as well as TiledImage. :smile:

**Comment by b005t3r** [comment]
Great, thanks for looking into these things, Daniel. Also great a lot of it is planned for the new version :)

As for 2): with the project I'm currently working on I have a couple of Sprites, were such batching is really helpful (I'm doing it manually from scratch at the moment). For example, my game uses hexes to display regions of a bigger map. Each hex is a quite complex object itself but doesn't really change very often, so it's a good idea to flatten it. But it also is a part of a bigger map with tens of other hexes, so it's also a good idea to flatten the whole map as well.
Problems with the current approach start when only one hex changes, because now all other hexes have to be flattened again as a part of flattening the map sprite, where in my approach I only have to flatten the one which actually did change and when flattening the map I can use the flattened hexes's data (which is faster than having to flatten every hex separately).
Also, could you write a bit more about this planned alternative to flattening? Maybe this is the thing I need.

**Comment by PrimaryFeather** [comment]
Okay, I understand the use-case now, thanks!

It's planned like this: the RenderSupport class (now: Painter) forwards all objects to the "BatchRenderer", which manages the batches and initiates all the drawing. That object will be a display object, too, so you can place it anywhere in your display tree and configure it in any way you need. The "flatten" call will use such an object, too.

... but that's a part that hasn't been written yet, so please take it with a grain of salt. :wink:

**Comment by b005t3r** [comment]
OK, so in my example I could have one BatchRenderer at the "map level" and another for each hex, at the "hex level" - the map one would batch all the hexes together and the hex ones would batch each hex separately? If so, I guess we're good here :smiley:

**Comment by PrimaryFeather** [comment]
I think so, yes! Let's see if it turns out like that. =)

**Comment by b005t3r** [comment]
BTW, just discovered that my idea for pixel perfect rendering will not work only for display objects not batched on separate batches (e.g. flattened Sprites) and I have no idea how to solve this :)

**Comment by b005t3r** [comment]
A couple more requests for feature version (versions) after doing some more coding with the current one (1.7?)

**1. DisplayObjects excluded from rendering.** Currently I do this by making them invisible (```obj.visible = false;```), but it doesn't seem elegant. It probably affects other things like touch events as well.
**2. DisplayObjects used for rendering only.** Opposite of the previous one. Sometimes I don't want some objects to contribute in bounds calculation and/or touch event handling. Currently I try not to add such objects to the stage and render them manually, but it doesn't work with all objects (e.g. Spine SkeletonAnimation with ```meshRendering == true``` has to be added to a parent to work).
**3. Fixed size Sprites (containers).** I noticed that most of the time I don't really need the automatic bounds validation - more often I need to set the size of my container (and sometimes resize it later), so it would be really great to be able to create a Sprite with a given width and height (and be able to adjust it after it's been created).

**Comment by PrimaryFeather** [comment]
For (1), you can set "alpha = 0.0". That will completely exclude an object from rendering, but will keep touch events and other things all intact.

For (2) and (3), there's nothing planned yet. At least for Sprites, though, it should be rather easy to implement that at application level by overriding "getBounds" and "hitTest". (You cannot attach such a behavior to existing objects like images, though; agreed.)

Thanks for the suggestions! BTW, I saw that I actually already implemented a huge part of your previous suggestions, Łukasz! For example, there's now a "RectangleUtil.getBounds" to simplify custom bounds checks; pixel snapping, Scale9 images, and auto-flattening. The "batching" request of your first post might become possible in the future, when I allow implementation of custom "BatchProcessors" (probably not part of 2.0, but the foundations are all in place.)

**Comment by b005t3r** [comment]
> BTW, I saw that I actually already implemented a huge part of your previous suggestions, Łukasz! For example, there's now a "RectangleUtil.getBounds" to simplify custom bounds checks; pixel snapping, Scale9 images, and auto-flattening. The "batching" request of your first post might become possible in the future, when I allow implementation of custom "BatchProcessors" (probably not part of 2.0, but the foundations are all in place.)

Yes, I'm keeping my eye on what you're doing with the 2.0 and I simply couldn't be any more grateful :) All the cool toys to play with just waiting for me there :)

> For (1), you can set "alpha = 0.0". That will completely exclude an object from rendering, but will keep touch events and other things all intact.

Not if I want to animate the alpha value from frame to frame :) As I said, the cleanest solution right now it setting ```visible = false``` just before doing default rendering, than setting it back to ```true``` and the doing the custom rendering. But it's not really elegant or convenient.

> For (2) and (3), there's nothing planned yet. At least for Sprites, though, it should be rather easy to implement that at application level by overriding "getBounds" and "hitTest". (You cannot attach such a behavior to existing objects like images, though; agreed.)

I can probably create my own ```FixedSizeSprite``` for my projects, this is not a problem (and it's how I'm doing it now), but I guess it would be a really useful thing to have as a part of the framework - it's very convenient and great for performance - I guess over 50% of my current project's ```Sprites``` are ```FixedSizeSprites```. As for other ```DisplayObjects``` excluded from bounds/touch/hit calculations it would be more of a workaround for these use cases where I need to work with third party Sprite subclasses (e.g. Feathers) and I don't want e.g. for my TextFields to change the parent's bounds.

As I said, all of this can be done with subclassing etc., but it's fiddly and probably hard to maintain if some of the classes I subclassed change. And making it a part of Starling doesn't seem like a such big deal, I guess - couple of ifs in the rendering/event handling loops and we're done :) Only risks I can see with these features is they are not really intuitive (once you add a ```DispplayObject``` to the stage you expect it to handle touch event and to render itself on the screen), but then again the default behavior would be to have the off, and you would only switch them on on particular objects if you really need it.

**Comment by PrimaryFeather** [comment]
I'll close this issue now, since it was mostly a discussion about what to integrate in Starling 2. A whole lot of your suggestions actually made it into the release — so thanks again for this fruitful discussion!

Anything that's still lacking should be opened up in a separate issue, so that we can discuss that on a case-by-case basis.
