### ISSUE TITLE
Starling 1.7, ATF: Error #3677: Texture decoding failed. Internal error.

### ISSUE THREAD

**Issue by santiagopuentep** [Gamua/Starling-Framework#782]
Hi.

We are getting a occasional Error #3677 error on Android when using an assetManager to load atlases for changing graphic themes in the app (which use a different set of atlases each). The app works correctly but after switching themes a few times it throws the error.

To switch themes we call `dispose()` followed by `purge()` and then load all the assets for the new theme.

We have ATF textures with ETC1+alpha encoding created using TexturePacker in 2048x2048.

Device: LG Nexus 5 Android 6

Updated to Starling 1.7 but the error is still there. We need to release this app ASAP, we ran out of options.

Please help!

**Comment by SebaSOFT** [comment]
We can provide Scout telemetry for this event...

**Comment by PrimaryFeather** [comment]
Hm ... you actually don't have to call "dispose", since "purge" will do that internally, anyway. Have you tried if the problem occurs without calling "dispose" manually? Perhaps the problem comes from the textures being disposed twice.

Have you tried this on multiple Android devices, and is the result always the same? Or maybe iOS?

**Comment by SebaSOFT** [comment]
Testing a version without dispose. Will provide telemetry including Stage3D's

**Comment by SebaSOFT** [comment]
Same problem, attaching telemetry

Download and rename as RAR
![kga019debug rar](https://cloud.githubusercontent.com/assets/2537716/11002962/ba9bab2c-848e-11e5-9501-9bc508bbc2e5.jpg)

**Comment by PrimaryFeather** [comment]
Two more questions:

* Have you tried this on multiple Android devices, and is the result always the same? Or maybe iOS?
* Which AIR version are you using? The most stable Android release was AIR 15, later releases had some problems (most of which have been solved in the recent releases, but still, it's worth a try).

**Comment by SebaSOFT** [comment]
* Currently on AIR 19, rolling back so many versions may arrise other problems with the game and other ANE
* Other devices suffer more or less is hard to differenciate if the leak is in starling or AIR itself

**Comment by PrimaryFeather** [comment]
One more thing to try - AIR 20 is currently in beta, and it changed some Android related things. Could you try that, instead?

Sent from mobile — please pardon brevity and/or errors.

**Comment by SebaSOFT** [comment]
I will try to test this, the release notes doesnt say anithing but upgrading the Native SDKs.

Thanks to you for providing this support, hopefully we can find this and (if it's in Starling) squash it together.

**Comment by PrimaryFeather** [comment]
You're welcome, doing what I can to help! :smile:

Yeah, there's nothing specific about the texture problem, but perhaps their dropping some backwards compatibility made some things easier on their side (harder to fail). I don't have too high hopes, but it's definitely worth a shot! 

(In any case, "internal errors" are very likely AIR problems; and the AssetManager code hasn't changed for a while. That's why I'm guessing a runtime fix might be our best hope.)

**Comment by PrimaryFeather** [comment]
Lacking any further comments, I'll close this issue for now. I hope it was resolved with an AIR update?
Feel free to open it again if you need further assistance.
