### ISSUE TITLE
Multiple Starling loaded in a parent

### ISSUE THREAD

**Issue by dolphin520** [Gamua/Starling-Framework#794]
HI Everyone!

I have a question here. 
Currently I have 2 swfs that have starling in them.
I open up a normal as3 project that dont have starling on it, i want to load both 2 swf with starling into this new project as child.

I want both swf is exist on the stage, but there will be only one swfs is visible at a time. 

I had try to load both swf file into the same stage.stage3ds[0] but i always can see the first swf i loaded only. the second one cannot be seen.

If i load them in different stage.stage3ds, the second swfs that i load in will cause Error.
[Fault] exception, information=ArgumentError: Error #3685: Could not create renderer.

How should I solve this? Please help! Thanks!

**Comment by PrimaryFeather** [comment]
First of all, sorry for the late reply!

To use two Starling instances at once, they need to share the 3D context (i.e. use the same Stage3D and Context3D). The reason why you didn't see anything when you tried that is because, per default, Starling will clear the back buffer once per frame; in your case, both Starling's were doing this once per frame, so only one of the two is visible.

Some information about how to share a 3D context can be found in the class documentation of the [Starling class](http://doc.starling-framework.org/current/starling/core/Starling.html); search for "sharing a 3D Context". In a nutshell, you're going to have to do some things manual that are otherwise automated by Starling — but it's doable.

Good luck!

**Comment by dolphin520** [comment]
Hi,

Thank you for your reply.
I have successfully loaded in the swf. Now I face a problem.

I load 2 swf into my container project. Both of this swf have a same class which is GloVar but the content is totally different. I load first swf and unload it then load second swf. In second swf, i try to get a variable from GloVar, second swf cannot get back it own GloVar variable, it get the first swf GloVar variable instead. When i load this 2 swf I use ApplicationDomain.currentDomain.

I had try to load this 2 swf using new ApplicationDomain(), but it have a Error popup saying that Starling Context is missing. May I know why is this happen?

Thanks a lot for your help.

**Comment by PrimaryFeather** [comment]
Unfortunately, I don't have much experience with such a setup myself; but I can see that this could lead to problems, having the same class names imported from two different SWF files. I think I can remember that unloading an SWF is not really possible ...

Couldn't you change the setup so that you just take the root classes (to be used with Starling) from the SWF files, and then create Starling in the main application? Those root classes also would need to have different names, or be in different packages, of course.

**Comment by PrimaryFeather** [comment]
Lacking any more replies, I'll close this issue for now. Feel free to open it up again when you want to continue this discussion!
