### ISSUE TITLE
if starling.showStats is set to true before root is created starling.showStats is false

### ISSUE THREAD

**Issue by SlavomirDurej** [Gamua/Starling-Framework#848]
This happens when you create instance of starling and add showStats property immediately
for example : 
```actionscript
    starling = new Starling(Root, stage, viewPort,null,"auto"); 
    starling .showStats = true;		
```
Before starling version 2.0 ,  starling .showStats would equal to true, now it equals to false.
Also stats objects in this case can no longer be gotten by :
```actionscript
    var stats:DisplayObject = stage.getChildAt(stage.numChildren-1) ;		
```

**Comment by PrimaryFeather** [comment]
Thanks a lot for the report! I fixed the issue that the getter did not return the correct value.

As for the second one: if you call `showStats = true` before adding your `ROOT_CREATED` event listener, you should be able to get the stats display just like before! Could you give that a try?

There's no way for me to fix that in a way that it also works the other way round, since Starling does not have event priorities.

Please let me know if that works for you!

**Comment by PrimaryFeather** [comment]
BTW, the Stage could theoretically also contain other content after the stats display. So a check like this would be safer:

```as3
var stage:starling.display.Stage = Starling.current.stage;

for (var i:int=0; i<stage.numChildren; ++i)
{
    var child:DisplayObject = stage.getChildAt(i);

    if (getQualifiedClassName(child) == "starling.core::StatsDisplay")
        trace("found stats display!");
}
```
