### ISSUE TITLE
GlowFilter "jiggling"

### ISSUE THREAD

**Issue by tconkling** [Gamua/Starling-Framework#856]
I'm converting my project to Starling 2.0 (from 1.8) and having a couple issues with the GlowFilter.

In 1.8, I was using `BlurFilter.createGlow(someColor, alpha=3.0, blur=1.0, resolution=0.5)` to create this effect:

![glow_1 8](https://cloud.githubusercontent.com/assets/709022/15034379/cede1164-1229-11e6-8407-657075ed382f.gif)

With Starling 2 (I've tried both with the 2.0.1 tag and the latest HEAD revision as of today), this code: `new GlowFilter(someColor, alpha=3.0, blur=1.0, resolution=0.5)` produces this result:

![glow_2 0](https://cloud.githubusercontent.com/assets/709022/15034445/ab9e1d56-122a-11e6-896c-1b275315bd04.gif)

(Ignore the fact that the character is no longer blue - that's related to a recoloring shader I haven't yet adapted for Starling 2, and not the blur filter.)

The strength of the glow is much less pronounced - it was possible to "overload" the alpha parameter in the previous version to get a really strong effect, but alpha is clamped at 1.0 in the new version. (Removing the `MathUtil.clamp` in `CompositeFilter.setAlphaAt` fixes this issue for me - can I issue a pull request for that, or is it important that the value be clamped for other clients of CompositeFilter?).

But more importantly, the animation with the GlowFilter applied is now jiggling quite a bit - like, its location on screen is being modified by the filter. It gets more pronounced as the bounds of the animated character grow and shrink more dramatically. Any thoughts on how to fix?

**Comment by PrimaryFeather** [comment]
Hey Tim,
first of all, I'm exciting to hear you're taking the step to upgrade to Starling 2! It's been a while since we last talked! :smile:

Removing the `clamp` should not be an issue at all; I'll have another look, though, if there was any specific reason for me to add that.
As for the jiggling: I recently noticed that myself when playing around; my best guess is that is has something to do with `pixelSnapping` something or `padding`. I'm sure I'll be able to fix that - I'll try to do so tomorrow or early next week.

(The reason that this can happen is that, different to Starling 1.x, the filter now combines object and blur into one texture. Before, glow and drop shadow were drawn underneath the un-modified object. That made some other things (caching!) very complicated, though, so I changed that.)

**Comment by PrimaryFeather** [comment]
That character looks awesome, by the way. :smile:

**Comment by tconkling** [comment]
Thanks Daniel!

**Comment by PrimaryFeather** [comment]
Hey Tim,
please try again! Both issues should be fixed now.

**Comment by tconkling** [comment]
Excellent, thanks Daniel! I'm out of town with no internet (except on my
phone), but I'll give it a try next week when I'm back!
