### ISSUE TITLE
the atf of etc2 without alpha not work on iphone5 

### ISSUE THREAD

**Issue by matrix3d** [Gamua/Starling-Framework#951]
the atf of etc2 with alpha work good on iphone5.

**Comment by PrimaryFeather** [comment]
That's very likely a problem / incompatibility of AIR; Starling can't do much about it.
I recommend you create an issue here: [Adobe Tracker](https://tracker.adobe.com/). Be sure to include a sample texture (both in the base PNG format as in the ATF format) and screenshots of the output you are seeing.

Then post a link to your bug report here, so that it's easier to find for other developers, and so that we can all vote for it.

Thanks in advance!

**Comment by matrix3d** [comment]
ok
