### ISSUE TITLE
Video texture artifacts

### ISSUE THREAD

**Issue by CrazyFlasher** [Gamua/Starling-Framework#953]
Hi.
I am playing video texture and it is fine on mobiles and some pcs.
But one pc with Intel® HD Graphics 2000 integrated graphics adapter I receive artifacts:
![codec_issue](https://cloud.githubusercontent.com/assets/1607138/24244089/296f5a08-0fc6-11e7-9644-554270a3ae68.jpg)
![lvl4_broken_safe](https://cloud.githubusercontent.com/assets/1607138/24245891/692aacfe-0fcd-11e7-8535-97688c4946b1.gif)

I play video using this way:
```
videoTexture = Texture.fromNetStream(netStream, 1, function():void
{
	videoImage = new Image(videoTexture);
	videoUI = new UIClip().setAssets(videoImage);
	addUIClip(videoUI);
		updateUIContainer();
});
netStream.play(hintListModel.suitableHintImmutable.videoURL);
```
If I play this video using some other players installed on PC - everything is fine. So the problem, not in video.
I am building with AIR 25 SDK, but tried lower versions also.

May be the reason is in the codec? What is the most compatible codec for mp4 videos and Starling / AIR?

Link to video file:
http://95.85.13.123:8080/hints/level_5/22-step.mp4

**Comment by PrimaryFeather** [comment]
The ideal codec for video is h.264 with AAC audio encoding (if there is audio). Which seems to be exactly what you are using. 😒 

Perhaps you could try to re-encode the video with another program? Perhaps your encoder simply used a feature that's compatible with the decoder used by the runtime. I'm no expert on this, but that's the first thing I would try.

Furthermore, create a bug report at [Adobe Tracker](http://tracker.adobe.com) and post the link to the report here, so that we can vote for it. Thanks in advance!

**Comment by PrimaryFeather** [comment]
Since this is purely a stage3d / device issue, I'll close this ticket for now.
