### ISSUE TITLE
Adobe stops flash support in 2020

### ISSUE THREAD

**Issue by Gargo** [Gamua/Starling-Framework#989]
https://blogs.adobe.com/conversations/2017/07/adobe-flash-update.html

do you plan still commit to this repository instead of for examjple Sparrow?

**Comment by PrimaryFeather** [comment]
That Flash approaches it's "end-of-life" does not affect Adobe AIR — what's going away is the Flash Player, not the platform for cross-platform development. Chris Campbell from Adobe clarified this on the Starling forum (see [this thread](https://forum.starling-framework.org/topic/air-roadmap-update)) shortly after the blog post above was published.

So, yes, I'm continuing to develop and support Starling, just like before!

**Comment by 22Round** [comment]
@PrimaryFeather my proposal would be support Haxe/OpenFL's Starling, Platform is stabile and is true cross platform solution.

**Comment by JohnBlackburne** [comment]
So is Adobe AIR, a stable, true cross platform solution. And it has the weight of Adobe behind it. It is not going away.

**Comment by 22Round** [comment]
@JohnBlackburne AIR is missing some platforms (Linux, Consoles,  Windows Phone)

**Comment by PrimaryFeather** [comment]
A port to HaXe is definitely not out of the question — after all, it would provide the smoothest transition for those who need an HTML target or don't want to rely on AIR.

On the other hand, I must admit I'm not sure yet if I'd be really able to bring much to the table. After all, there are already a couple of great HaXe libraries, and especially OpenFL is already a port of the Flash API to HaXe. Why would people use Starling.HaXe for a new project instead of OpenFL or its alternatives?

**Comment by johnridges** [comment]
You would want to use Staling.HaXe with OpenFL for exactly the same reasons you want Starling in Flash: to put a friendly framework around the Stage3D classes. In fact, there is already a port of Starling 1.8 to HaXe in the OpenFL repository (as well as Away3D).

I agree that if you're not using OpenFL (and folks starting new HaXe projects likely wouldn't) then Starling.HaXe wouldn't be of much use. But it would be very useful for people porting Flash projects that use Starling over to HaXe.
